import contextlib
import datetime
import json
import os
from typing import LiteralString

import psycopg
from psycopg.types.json import Jsonb

from rung import text
from rung.models import (
    CompanyReconRecord,
    CompanyStoreRecord,
    DispensaryRecord,
    LocationObservation,
    StateProgramRecord,
    StoreProductRecord,
)

type DBConn = psycopg.Connection

_DEFAULT_DATABASE_URL = "postgresql://dispensary:dispensary@localhost:5432/dispensaries"

_CREATE_DISPENSARIES = """
CREATE TABLE IF NOT EXISTS dispensaries (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source            TEXT    NOT NULL,
    name              TEXT,
    address           TEXT,
    city              TEXT,
    state             TEXT,
    zip_code          TEXT,
    phone             TEXT,
    website           TEXT,
    latitude          DOUBLE PRECISION,
    longitude         DOUBLE PRECISION,
    scraped_at        TEXT    NOT NULL
)
"""

# company_id logically references companies(id), but the companies table is owned
# (and created later) by seed_companies.py, so no FK constraint — Postgres would
# reject DDL referencing a not-yet-existing table. SQLite never enforced it either.
_CREATE_COMPANY_RECON = """
CREATE TABLE IF NOT EXISTS company_recon (
    company_id     INTEGER NOT NULL,
    canonical_name TEXT    NOT NULL,
    homepage_url   TEXT,
    platform       TEXT,
    confidence     TEXT,
    http_status    INTEGER,
    error          TEXT,
    scouted_at     TEXT    NOT NULL,
    PRIMARY KEY (company_id)
)
"""

_CREATE_COMPANY_STORES = """
CREATE TABLE IF NOT EXISTS company_stores (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id     INTEGER NOT NULL,
    canonical_name TEXT    NOT NULL,
    state          TEXT    NOT NULL,
    source         TEXT    NOT NULL,
    name           TEXT,
    address        TEXT,
    city           TEXT,
    zip_code       TEXT,
    phone          TEXT,
    website        TEXT,
    latitude       DOUBLE PRECISION,
    longitude      DOUBLE PRECISION,
    platform       TEXT,
    external_id    TEXT,
    store_url      TEXT,
    canonical_company_id INTEGER,
    storefront_name TEXT,
    scraped_at     TEXT    NOT NULL
)
"""

# Scrape-handle columns added after company_stores first shipped; create_tables
# adds any missing so existing databases upgrade in place. canonical_company_id is
# set by the dedupe step: NULL = this row is canonical/unique; non-NULL points to the
# operator's canonical company (the row is a shared-brand duplicate, e.g. Delta 9 /
# Keystone IC stores that are really Sunnyside).
_COMPANY_STORE_ADDED_COLUMNS = {
    "platform": "TEXT",
    "external_id": "TEXT",
    "store_url": "TEXT",
    "canonical_company_id": "INTEGER",
    # The brand on THIS location's storefront (the alias name where one applies),
    # for reporting. Distinct from the operator (the dedup/grouping key).
    "storefront_name": "TEXT",
}

_INSERT_DISPENSARY = """
INSERT INTO dispensaries
  (source, name, address, city, state, zip_code, phone,
   website, latitude, longitude, scraped_at)
VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
"""

_UPSERT_RECON = """
INSERT INTO company_recon
  (company_id, canonical_name, homepage_url, platform, confidence,
   http_status, error, scouted_at)
VALUES (%s,%s,%s,%s,%s,%s,%s,%s)
ON CONFLICT (company_id) DO UPDATE SET
  canonical_name = excluded.canonical_name,
  homepage_url   = excluded.homepage_url,
  platform       = excluded.platform,
  confidence     = excluded.confidence,
  http_status    = excluded.http_status,
  error          = excluded.error,
  scouted_at     = excluded.scouted_at
"""

_CREATE_ACCESS_METHODS = """
CREATE TABLE IF NOT EXISTS access_methods (
    target_type  TEXT    NOT NULL,
    target_key   TEXT    NOT NULL,
    method       TEXT    NOT NULL,
    cost_rank    INTEGER NOT NULL,
    status       TEXT    NOT NULL DEFAULT 'never',
    resource_url TEXT,
    params       TEXT,
    record_count INTEGER,
    error        TEXT,
    attempts     INTEGER NOT NULL DEFAULT 0,
    last_ok_at   TEXT,
    last_fail_at TEXT,
    updated_at   TEXT    NOT NULL,
    PRIMARY KEY (target_type, target_key, method)
)
"""

# Transient per-run work items (claims close the documented concurrency hazards —
# see docs/stage_contracts.md §5). Companion to access_methods, which is the
# DURABLE per-target memory; jobs rows are run bookkeeping. timestamptz here
# (unlike the TEXT timestamps elsewhere) because the requeue-timeout math runs in SQL.
_CREATE_JOBS = """
CREATE TABLE IF NOT EXISTS jobs (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_type    TEXT NOT NULL,
    target_key   TEXT NOT NULL,
    payload      JSONB,
    status       TEXT NOT NULL DEFAULT 'pending',
    attempts     INTEGER NOT NULL DEFAULT 0,
    max_attempts INTEGER NOT NULL DEFAULT 3,
    claimed_by   TEXT,
    claimed_at   TIMESTAMPTZ,
    scheduled_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at  TIMESTAMPTZ,
    error        TEXT
)
"""

# Dedupes LIVE jobs per (task_type, target_key) while letting done/failed rows
# accumulate as run history. Also indexes the claim predicate.
_CREATE_JOBS_LIVE_UNIQUE = """
CREATE UNIQUE INDEX IF NOT EXISTS jobs_live_unique
    ON jobs (task_type, target_key) WHERE status IN ('pending', 'claimed')
"""

# Partial index over just the CLAIMABLE rows, matching the claim scan's shape
# (WHERE task_type=… AND status='pending' AND scheduled_at<=now() ORDER BY id LIMIT 1). As
# done/failed history accumulates between prunes the live-unique index above still spans every
# status; this one covers only pending rows so the FOR UPDATE SKIP LOCKED claim stays an
# index-only scan of the tiny working set. See docs/distributed_scraping_design.md §4-5.
_CREATE_JOBS_PENDING_CLAIM = """
CREATE INDEX IF NOT EXISTS jobs_pending_claim ON jobs (task_type, id) WHERE status = 'pending'
"""

# jobs columns added after the table's first release — applied in-place by _migrate_jobs so an
# existing database picks them up. lease/heartbeat back the distributed-worker lease + SKIP-LOCKED
# reaper (queue.reap_expired / bump_heartbeat); see docs/distributed_scraping_design.md §4-5. A
# claim stamps both; a long-running worker bumps last_heartbeat/lease_until; the reaper re-queues a
# claim whose lease_until has passed (a crashed/hung worker), so a dead worker no longer wedges a job.
_JOBS_ADDED_COLUMNS = {
    "lease_until": "TIMESTAMPTZ",
    "last_heartbeat": "TIMESTAMPTZ",
}

# Durable cross-worker proxy health, keyed per (proxy_url × host) — a proxy can be fine on Dutchie
# but banned on Weedmaps, so health is tracked per host. Public infra (the DDL); the selection/health
# POLICY (claim the healthiest, disable after N consecutive fails + cooldown) is private
# (rung_intel.proxy_store). See docs/distributed_scraping_design.md §2.1/§3.
_CREATE_PROXIES = """
CREATE TABLE IF NOT EXISTS proxies (
    proxy_url         TEXT    NOT NULL,
    host              TEXT    NOT NULL,
    success_count     INTEGER NOT NULL DEFAULT 0,
    error_count       INTEGER NOT NULL DEFAULT 0,
    consecutive_fails INTEGER NOT NULL DEFAULT 0,
    disabled_until    TIMESTAMPTZ,
    last_used_at      TIMESTAMPTZ,
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (proxy_url, host)
)
"""
# The claim scan picks the healthiest non-disabled proxy for a host (order by consecutive_fails,
# last_used_at). Partial over the not-disabled fast path (the common case) so the scan is index-only.
_CREATE_PROXIES_CLAIM_INDEX = """
CREATE INDEX IF NOT EXISTS proxies_host_health ON proxies (host, consecutive_fails, last_used_at)
    WHERE disabled_until IS NULL
"""

# Per-platform egress-tier registry. One row per menu/store platform recording which proxy tier
# (direct/datacenter/residential) it should scrape through, the escalation-gate block rate that
# decided it, and where the decision came from. Public infra (the DDL, like `proxies`); the
# selection POLICY (config default + this override) is private (rung_intel.proxy_tiers).
# See docs/distributed_scraping_design.md §0 (escalation gate) / §1 (tiers).
_CREATE_PROXY_TIERS = """
CREATE TABLE IF NOT EXISTS proxy_tiers (
    platform        TEXT PRIMARY KEY,
    tier            TEXT NOT NULL,
    block_rate_pct  DOUBLE PRECISION,
    source          TEXT,
    decided_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
)
"""

# Cross-worker per-host rate limiter (token bucket). One row per host: `tokens` is the current
# allowance, refilled at `rate_per_sec` up to `burst` on each access using `now() - last_refill` as
# the elapsed clock. Public infra (like `jobs`); the refill/deduct policy lives in `rate_limit.py`
# and the aggregator-path integration is private (overlay). See docs/distributed_scraping_design.md §3-4.
_CREATE_TOKEN_BUCKETS = """
CREATE TABLE IF NOT EXISTS token_buckets (
    host        TEXT PRIMARY KEY,
    tokens      DOUBLE PRECISION NOT NULL,
    last_refill TIMESTAMPTZ NOT NULL DEFAULT now()
)
"""

# Stage-3 menu snapshots. Keyed by store_key (= "{platform}:{external_id}") rather
# than company_stores.id because the keep-the-best replace regenerates store ids;
# company_id/state ride along for joins and per-state reporting.
_CREATE_STORE_PRODUCTS = """
CREATE TABLE IF NOT EXISTS store_products (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          INTEGER NOT NULL,
    state               TEXT    NOT NULL,
    store_key           TEXT    NOT NULL,
    platform            TEXT    NOT NULL,
    external_id         TEXT    NOT NULL,
    source              TEXT    NOT NULL,
    external_product_id TEXT,
    name                TEXT,
    brand               TEXT,
    category            TEXT,
    category_std        TEXT,
    product_type_std    TEXT,
    strain_type         TEXT,
    strain_type_std     TEXT,
    price               DOUBLE PRECISION,
    size_g              DOUBLE PRECISION,
    thc                 DOUBLE PRECISION,
    cbd                 DOUBLE PRECISION,
    thc_mg              DOUBLE PRECISION,
    cbd_mg              DOUBLE PRECISION,
    terpenes            JSONB,
    terpenes_std        JSONB,
    terp_total          DOUBLE PRECISION,
    cannabinoids_std    JSONB,
    variants            JSONB,
    scraped_at          TEXT    NOT NULL,
    -- The percent-OR-mg potency contract (CLAUDE.md): a cannabinoid is published as a percent
    -- (thc/cbd) OR a per-dose mg (thc_mg/cbd_mg), never both. The extractors route by the
    -- platform's unit; this makes the invariant a schema guarantee, not just a convention.
    CONSTRAINT store_products_potency_unit_check
        CHECK ((thc IS NULL OR thc_mg IS NULL) AND (cbd IS NULL OR cbd_mg IS NULL))
)
"""

# store_products columns added after the table's first release — applied in-place by
# _migrate_store_products so an existing database picks them up.
_STORE_PRODUCT_ADDED_COLUMNS = {
    "thc_mg": "DOUBLE PRECISION",
    "cbd_mg": "DOUBLE PRECISION",
    "category_std": "TEXT",
    "product_type_std": "TEXT",
    "strain_type_std": "TEXT",
    "size_g": "DOUBLE PRECISION",
    "terpenes_std": "JSONB",
    "terp_total": "DOUBLE PRECISION",
    "cannabinoids_std": "JSONB",
}

# The percent-OR-mg potency CHECK, added in-place to a database created before the constraint
# existed. Postgres has no ADD CONSTRAINT IF NOT EXISTS, so the DO block swallows duplicate_object
# to stay idempotent (a fresh table already carries the constraint from _CREATE_STORE_PRODUCTS).
# Pre-flight scan 2026-07-02: 0 of 4.8M live rows violate it, so it validates without cleanup.
_MIGRATE_STORE_PRODUCTS_POTENCY_CHECK = """
DO $$ BEGIN
    ALTER TABLE store_products ADD CONSTRAINT store_products_potency_unit_check
        CHECK ((thc IS NULL OR thc_mg IS NULL) AND (cbd IS NULL OR cbd_mg IS NULL));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
"""

_CREATE_STORE_PRODUCTS_STORE_INDEX = """
CREATE INDEX IF NOT EXISTS store_products_store_key ON store_products (store_key)
"""

# Per-state read paths. `store_products` (4.8M rows) is grouped by store_key per state once at
# every `scrape-menus` startup (`latest_snapshot_times`) — a `(state, store_key)` index turns that
# from a full scan into an index-only scan (the `(store_key)` index above stays for the per-store
# `WHERE store_key = %s` lookups). `company_stores` is filtered by `(company_id, state)` five times
# per company in the Stage-2 keep-the-best replace and by `state` alone in dedupe/compare; a
# `(state, company_id)` composite serves both (two equality predicates + the leftmost-prefix
# state-only scans).
_CREATE_STORE_PRODUCTS_STATE_INDEX = """
CREATE INDEX IF NOT EXISTS store_products_state_store_key ON store_products (state, store_key)
"""
_CREATE_COMPANY_STORES_STATE_INDEX = """
CREATE INDEX IF NOT EXISTS company_stores_state_company ON company_stores (state, company_id)
"""

# Master product DB. `store_products` stays the live
# snapshot (overwritten each scrape); these two tables accumulate HISTORY the snapshot throws away.
# `products` = one row per distinct product ever seen (identity = the text.product_fingerprint tuple,
# potency/terpenes excluded since they vary by batch). `product_observations` = an APPEND-ONLY log of
# price/potency/terpenes stamped with scraped_at — never updated, never deleted — the substrate for
# longitudinal analyses. Scoped to consumable categories (_OBSERVED_CATEGORIES); a plain indexed
# table (partition later if it grows).
_CREATE_PRODUCTS = """
CREATE TABLE IF NOT EXISTS products (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fingerprint      TEXT NOT NULL UNIQUE,
    brand            TEXT,
    name             TEXT,
    category_std     TEXT,
    product_type_std TEXT,
    strain_type_std  TEXT,
    size_g           DOUBLE PRECISION,
    first_seen       TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen        TIMESTAMPTZ NOT NULL DEFAULT now()
)
"""
_CREATE_PRODUCT_OBSERVATIONS = """
CREATE TABLE IF NOT EXISTS product_observations (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id    BIGINT  NOT NULL,
    store_key     TEXT    NOT NULL,
    state         TEXT    NOT NULL,
    price         DOUBLE PRECISION,
    thc           DOUBLE PRECISION,
    cbd           DOUBLE PRECISION,
    thc_mg        DOUBLE PRECISION,
    cbd_mg        DOUBLE PRECISION,
    terpenes_std  JSONB,
    terp_total    DOUBLE PRECISION,
    cannabinoids_std JSONB,
    scraped_at    TIMESTAMPTZ NOT NULL
)
"""
# product_observations columns added after first release — applied by _migrate_product_observations.
_PRODUCT_OBSERVATIONS_ADDED_COLUMNS = {
    "cannabinoids_std": "JSONB",
}
_CREATE_PRODUCT_OBSERVATIONS_PRODUCT_INDEX = """
CREATE INDEX IF NOT EXISTS product_observations_product ON product_observations (product_id, scraped_at)
"""
_CREATE_PRODUCT_OBSERVATIONS_STORE_INDEX = """
CREATE INDEX IF NOT EXISTS product_observations_store ON product_observations (store_key, scraped_at)
"""

# Store-lifecycle history. `company_stores` stays the live snapshot (overwritten each scrape);
# these two accumulate the history the snapshot throws away — the substrate for open/close/acquired
# detection (see docs/store_history_design.md). `store_locations` = one row per distinct PHYSICAL
# location ever seen (identity = the dedupe geo_key/address_key, computed in the overlay since the
# key builders live in sources/dedupe.py); `store_observations` = an APPEND-ONLY log of the operator
# / storefront / menu-handle seen at that location, stamped with observed_at — never updated or
# deleted. Change-detected + a daily presence heartbeat, exactly like product_observations.
_CREATE_STORE_LOCATIONS = """
CREATE TABLE IF NOT EXISTS store_locations (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_key  TEXT NOT NULL UNIQUE,
    state         TEXT,
    latitude      DOUBLE PRECISION,
    longitude     DOUBLE PRECISION,
    address       TEXT,
    city          TEXT,
    zip_code      TEXT,
    first_seen    TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen     TIMESTAMPTZ NOT NULL DEFAULT now()
)
"""
_CREATE_STORE_OBSERVATIONS = """
CREATE TABLE IF NOT EXISTS store_observations (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id   BIGINT NOT NULL,
    source        TEXT   NOT NULL,
    operator      TEXT,
    storefront_name TEXT,
    platform      TEXT,
    external_id   TEXT,
    address       TEXT,
    city          TEXT,
    observed_at   TIMESTAMPTZ NOT NULL
)
"""
_CREATE_STORE_OBSERVATIONS_LOCATION_INDEX = """
CREATE INDEX IF NOT EXISTS store_observations_location ON store_observations (location_id, observed_at)
"""

# The combined cross-platform surface: one row per product carrying only the standardized
# fields (canonical category, grams, percent/mg potency, the price-per-gram derived from the
# representative size, and the folded terpenes). The raw platform-shaped columns
# (category/terpenes/variants) stay on store_products; this view is what callers query for
# apples-to-apples comparison across platforms and states.
_CREATE_PRODUCTS_NORMALIZED_VIEW = """
CREATE OR REPLACE VIEW products_normalized AS
SELECT
    id, company_id, state, store_key, platform, source, external_product_id,
    name, brand, category_std AS category, strain_type_std AS strain_type,
    price, size_g,
    CASE WHEN size_g > 0 AND price IS NOT NULL
         THEN round((price / size_g)::numeric, 2) END AS price_per_g,
    thc, cbd, thc_mg, cbd_mg, terp_total, terpenes_std,
    scraped_at,
    product_type_std AS product_type,
    cannabinoids_std  -- appended last: CREATE OR REPLACE VIEW only allows adding columns at the end
FROM store_products
"""

_INSERT_STORE_PRODUCT = """
INSERT INTO store_products
  (company_id, state, store_key, platform, external_id, source,
   external_product_id, name, brand, category, category_std, product_type_std,
   strain_type, strain_type_std,
   price, size_g, thc, cbd, thc_mg, cbd_mg, terpenes, terpenes_std, terp_total,
   cannabinoids_std, variants, scraped_at)
VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
"""

_INSERT_COMPANY_STORE = """
INSERT INTO company_stores
  (company_id, canonical_name, state, source, name, address, city,
   zip_code, phone, website, latitude, longitude, platform, external_id,
   store_url, scraped_at)
VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
"""


def get_connection() -> DBConn:
    """Open and return a connection to the dispensaries database.

    Reads DATABASE_URL from the environment (default: local dev Postgres container).
    """
    url = os.environ.get("DATABASE_URL", _DEFAULT_DATABASE_URL)
    try:
        return psycopg.connect(url)
    except psycopg.OperationalError as exc:
        raise psycopg.OperationalError(
            f"{exc} — is the dev Postgres running?"
        ) from exc


def one(conn: DBConn, query: LiteralString, params: tuple = ()) -> tuple:
    """Run a query expected to return exactly one row and return it (never None).

    For aggregate / ``RETURNING`` / single-row SELECTs where ``fetchone()`` is logically non-None.
    Centralizes the ``Row | None`` narrowing so callers (esp. analysis scripts) can subscript the
    result directly without a per-call ``assert``. Raises if the query yields no row.
    """
    row = conn.execute(query, params).fetchone()
    if row is None:
        raise LookupError("query returned no row")
    return row


def create_tables(conn: DBConn) -> None:
    """Create all tables if they do not already exist.

    Does not create the companies table — that is owned by seed_companies.py.
    """
    conn.execute(_CREATE_DISPENSARIES)
    conn.execute(_CREATE_COMPANY_RECON)
    conn.execute(_CREATE_COMPANY_STORES)
    conn.execute(_CREATE_ACCESS_METHODS)
    conn.execute(_CREATE_STATE_PROGRAMS)
    conn.execute(_CREATE_JOBS)
    conn.execute(_CREATE_JOBS_LIVE_UNIQUE)
    conn.execute(_CREATE_JOBS_PENDING_CLAIM)
    _migrate_jobs(conn)
    conn.execute(_CREATE_TOKEN_BUCKETS)
    conn.execute(_CREATE_PROXIES)
    conn.execute(_CREATE_PROXIES_CLAIM_INDEX)
    conn.execute(_CREATE_PROXY_TIERS)
    conn.execute(_CREATE_STORE_PRODUCTS)
    conn.execute(_CREATE_STORE_PRODUCTS_STORE_INDEX)
    conn.execute(_CREATE_STORE_PRODUCTS_STATE_INDEX)
    conn.execute(_CREATE_COMPANY_STORES_STATE_INDEX)
    conn.execute(_CREATE_PRODUCTS)
    conn.execute(_CREATE_PRODUCT_OBSERVATIONS)
    conn.execute(_CREATE_PRODUCT_OBSERVATIONS_PRODUCT_INDEX)
    conn.execute(_CREATE_PRODUCT_OBSERVATIONS_STORE_INDEX)
    conn.execute(_CREATE_STORE_LOCATIONS)
    conn.execute(_CREATE_STORE_OBSERVATIONS)
    conn.execute(_CREATE_STORE_OBSERVATIONS_LOCATION_INDEX)
    _migrate_company_stores(conn)
    _migrate_state_programs(conn)
    _migrate_store_products(conn)
    _migrate_product_observations(conn)
    _migrate_dispensaries(conn)
    conn.execute(_CREATE_PRODUCTS_NORMALIZED_VIEW)  # after the migration adds its columns
    conn.commit()


# dispensaries columns removed after first release — always-NULL dead columns never set by any
# extractor or read back (audit L-19); dropped in-place from an older database.
_DISPENSARY_DROPPED_COLUMNS = ("product_available", "open_date", "open_on")


def _migrate_dispensaries(conn: DBConn) -> None:
    """Drop the dead always-NULL columns from an older database (audit L-19)."""
    for column in _DISPENSARY_DROPPED_COLUMNS:
        # DDL with a hardcoded column name from an all-literal module constant (LiteralString).
        conn.execute(f"ALTER TABLE dispensaries DROP COLUMN IF EXISTS {column}")


def _migrate_product_observations(conn: DBConn) -> None:
    """Add any product_observations columns missing from an older database."""
    for column, col_type in _PRODUCT_OBSERVATIONS_ADDED_COLUMNS.items():
        # DDL with hardcoded column/type from a module constant (see _migrate_company_stores).
        conn.execute(  # ty: ignore[no-matching-overload]
            f"ALTER TABLE product_observations ADD COLUMN IF NOT EXISTS {column} {col_type}"
        )


def _migrate_jobs(conn: DBConn) -> None:
    """Add any jobs columns missing from an older database (the lease/heartbeat columns)."""
    for column, col_type in _JOBS_ADDED_COLUMNS.items():
        # DDL with hardcoded column/type from a module constant (see _migrate_company_stores).
        conn.execute(  # ty: ignore[no-matching-overload]
            f"ALTER TABLE jobs ADD COLUMN IF NOT EXISTS {column} {col_type}"
        )


def _migrate_store_products(conn: DBConn) -> None:
    """Add any store_products columns missing from an older database, then the potency CHECK."""
    for column, col_type in _STORE_PRODUCT_ADDED_COLUMNS.items():
        # DDL with hardcoded column/type from a module constant (see _migrate_company_stores).
        conn.execute(  # ty: ignore[no-matching-overload]
            f"ALTER TABLE store_products ADD COLUMN IF NOT EXISTS {column} {col_type}"
        )
    conn.execute(_MIGRATE_STORE_PRODUCTS_POTENCY_CHECK)


def _migrate_company_stores(conn: DBConn) -> None:
    """Add any company_stores columns missing from an older database."""
    for column, col_type in _COMPANY_STORE_ADDED_COLUMNS.items():
        # DDL with hardcoded column/type from a module constant — not a LiteralString
        # to the stub, but no user input ever reaches it.
        conn.execute(  # ty: ignore[no-matching-overload]
            f"ALTER TABLE company_stores ADD COLUMN IF NOT EXISTS {column} {col_type}"
        )


def _migrate_state_programs(conn: DBConn) -> None:
    """Add any state_programs columns missing from an older database."""
    for column, col_type in _STATE_PROGRAM_ADDED_COLUMNS.items():
        # DDL with hardcoded column/type from a module constant (see above).
        conn.execute(  # ty: ignore[no-matching-overload]
            f"ALTER TABLE state_programs ADD COLUMN IF NOT EXISTS {column} {col_type}"
        )


def insert_dispensary(conn: DBConn, record: DispensaryRecord) -> None:
    """Insert one DispensaryRecord. Caller must commit."""
    now = datetime.datetime.now(datetime.UTC).isoformat()
    conn.execute(
        _INSERT_DISPENSARY,
        (
            record.source,
            record.name,
            record.address,
            record.city,
            record.state,
            record.zip_code,
            record.phone,
            record.website,
            record.latitude,
            record.longitude,
            now,
        ),
    )


def upsert_recon(conn: DBConn, record: CompanyReconRecord) -> None:
    """Upsert one CompanyReconRecord. Caller must commit."""
    now = datetime.datetime.now(datetime.UTC).isoformat()
    conn.execute(
        _UPSERT_RECON,
        (
            record.company_id,
            record.canonical_name,
            record.homepage_url,
            record.platform,
            record.confidence,
            record.http_status,
            record.error,
            now,
        ),
    )


def insert_company_store(conn: DBConn, record: CompanyStoreRecord) -> None:
    """Insert one CompanyStoreRecord. Caller must commit."""
    now = datetime.datetime.now(datetime.UTC).isoformat()
    conn.execute(
        _INSERT_COMPANY_STORE,
        (
            record.company_id,
            record.canonical_name,
            record.state,
            record.source,
            record.name,
            record.address,
            record.city,
            record.zip_code,
            record.phone,
            record.website,
            record.latitude,
            record.longitude,
            record.platform,
            record.external_id,
            record.store_url,
            now,
        ),
    )


def delete_company_stores_for_company(conn: DBConn, company_id: int, abbr: str) -> int:
    """Delete one company's store rows in a state so its re-scrape replaces them.

    Per-company (not whole-state) so a transient zero-yield for one company never
    wipes another company's good rows. Returns rows deleted; caller must commit.
    """
    cur = conn.execute(
        "DELETE FROM company_stores WHERE company_id = %s AND state = %s",
        (company_id, abbr),
    )
    return cur.rowcount


def count_company_stores(conn: DBConn, company_id: int, abbr: str) -> int:
    """How many stores are currently stored for one company in a state."""
    row = conn.execute(
        "SELECT COUNT(*) FROM company_stores WHERE company_id = %s AND state = %s",
        (company_id, abbr),
    ).fetchone()
    return row[0] if row else 0


def _distinct_stored_stores(conn: DBConn, company_id: int, abbr: str) -> int:
    """Stored DISTINCT physical stores (by address, name as fallback) for a company."""
    row = conn.execute(
        "SELECT COUNT(DISTINCT lower(coalesce(nullif(trim(address), ''), name, ''))) "
        "FROM company_stores WHERE company_id = %s AND state = %s",
        (company_id, abbr),
    ).fetchone()
    return row[0] if row else 0


def _distinct_new_stores(records: list[CompanyStoreRecord]) -> int:
    """Distinct physical stores in a scrape result (mirrors _distinct_stored_stores)."""
    return len({
        ((record.address or "").strip() or record.name or "").lower()
        for record in records
    })


# Weedmaps/Leafly are last-resort DIRECTORY listings: a handle exists, but the operator's
# real menu usually isn't there (their Stage-3 rungs frequently return empty). A store
# discovered via a real platform rung (Jane/Dutchie/Sweed/Cresco/Hytiva/Trulieve/Curaleaf —
# whose `platform` may even read "custom") is "menu-bearing" and worth more than an
# aggregator row. So keep-the-best prefers the result with MORE menu-bearing stores even at
# a total-count loss, and never downgrades menu-bearing stores to aggregator-only ones.
_AGGREGATOR_SOURCES = frozenset({"weedmaps_directory", "leafly_directory"})
_AGGREGATOR_PLATFORMS = frozenset({"weedmaps", "leafly"})


def _distinct_stored_menu_stores(conn: DBConn, company_id: int, abbr: str) -> int:
    """Stored DISTINCT physical stores carrying a NON-aggregator (real-menu-rung) handle."""
    row = conn.execute(
        "SELECT COUNT(DISTINCT lower(coalesce(nullif(trim(address), ''), name, ''))) "
        "FROM company_stores WHERE company_id = %s AND state = %s "
        "AND external_id IS NOT NULL AND external_id != '' "
        "AND coalesce(source, '') NOT IN ('weedmaps_directory', 'leafly_directory') "
        "AND coalesce(platform, '') NOT IN ('weedmaps', 'leafly')",
        (company_id, abbr),
    ).fetchone()
    return row[0] if row else 0


def _distinct_new_menu_stores(records: list[CompanyStoreRecord]) -> int:
    """Distinct physical stores in a scrape result carrying a non-aggregator handle."""
    return len({
        ((record.address or "").strip() or record.name or "").lower()
        for record in records
        if record.external_id
        and (record.source or "") not in _AGGREGATOR_SOURCES
        and (record.platform or "") not in _AGGREGATOR_PLATFORMS
    })


# A handle-upgrade may overwrite slightly fewer stores only if it retains at least this
# fraction of them — the Stage-3 `external_id` is worth a small count loss, a big one isn't.
_HANDLE_UPGRADE_RETENTION = 0.8

# A real-menu-handle upgrade (aggregator/plain → Jane/Dutchie/…) may lose more stores than a
# bare handle-upgrade — empty aggregator rows are low-value — but must still retain at least
# this fraction (so a real 15→1 collapse is rejected while a 4→3 menu upgrade is accepted).
_MENU_UPGRADE_RETENTION = 0.5


def replace_company_stores(
    conn: DBConn,
    company_id: int,
    abbr: str,
    records: list[CompanyStoreRecord],
) -> tuple[int, bool]:
    """Guarded, quality-aware keep-the-best replace of one company's stores. Caller commits.

    Overwrites the company's rows when the new scrape yields **at least as many** stores as
    are stored (so a transient zero/low-yield re-run can't clobber good data) — and, on a
    tie, the fresher result wins. Both sides are counted as DISTINCT physical stores
    (address, name as fallback), not raw rows, so a noisy extractor that emitted two rows
    per store can't entrench itself against a clean result. As a quality refinement, a new
    result that adds Stage-3 ``external_id`` handles where the stored rows have none also
    wins even if it has slightly fewer stores (it must retain ≥
    ``_HANDLE_UPGRADE_RETENTION`` of them), since a store row with a menu handle is worth
    more than a bare address.

    Quality dominates count among menu-platform handles (Jane/Dutchie/Sweed/… — NOT the
    Weedmaps/Leafly directory listings, whose menus are usually empty): a result with **more**
    of them wins as long as it retains ≥ ``_MENU_UPGRADE_RETENTION`` of the stores (so 4 empty
    Leafly listings yield to 3 Jane handles, but a 15→1 collapse is still rejected), and a
    result with **fewer** never clobbers (no downgrading real menus to a bigger empty-aggregator
    sweep). Only when both sides have the same menu-platform count does the distinct-count /
    freshness / handle-upgrade logic below decide. Returns ``(resulting_count, kept_prior)`` —
    ``kept_prior`` is True when better prior data was retained.
    """
    existing = count_company_stores(conn, company_id, abbr)
    if not records:
        return existing, False

    existing_distinct = _distinct_stored_stores(conn, company_id, abbr)
    new_distinct = _distinct_new_stores(records)
    existing_menu = _distinct_stored_menu_stores(conn, company_id, abbr)
    new_menu = _distinct_new_menu_stores(records)
    if new_menu < existing_menu:
        # Never downgrade real-menu handles to fewer of them (or to aggregator-only rows),
        # even if the new set has more total stores — protects a Jane/Dutchie set from a
        # transient low-yield re-scrape or a larger empty-aggregator sweep.
        overwrite = False
    elif new_menu > existing_menu:
        # Gained real-menu handles (e.g. 4 empty Leafly listings → 3 Jane handles): accept
        # unless it would lose more than half the stores (a 15→1 collapse is still rejected).
        overwrite = new_distinct >= existing_distinct * _MENU_UPGRADE_RETENTION
    else:
        overwrite = new_distinct >= existing_distinct
        if not overwrite:
            handle_row = conn.execute(
                "SELECT COUNT(*) FROM company_stores WHERE company_id = %s AND state = %s "
                "AND external_id IS NOT NULL AND external_id != ''",
                (company_id, abbr),
            ).fetchone()
            existing_handles = handle_row[0] if handle_row else 0
            new_handles = sum(1 for record in records if record.external_id)
            overwrite = (
                existing_handles == 0
                and new_handles > 0
                and new_distinct >= existing_distinct * _HANDLE_UPGRADE_RETENTION
            )
    if not overwrite:
        return existing, True

    delete_company_stores_for_company(conn, company_id, abbr)
    for record in records:
        insert_company_store(conn, record)
    return len(records), False


def insert_store_product(conn: DBConn, record: StoreProductRecord) -> None:
    """Insert one StoreProductRecord. Caller must commit."""
    now = datetime.datetime.now(datetime.UTC).isoformat()
    conn.execute(
        _INSERT_STORE_PRODUCT,
        (
            record.company_id,
            record.state,
            record.store_key,
            record.platform,
            record.external_id,
            record.source,
            record.external_product_id,
            record.name,
            record.brand,
            record.category,
            record.category_std,
            record.product_type_std,
            record.strain_type,
            record.strain_type_std,
            record.price,
            record.size_g,
            record.thc,
            record.cbd,
            record.thc_mg,
            record.cbd_mg,
            Jsonb(record.terpenes) if record.terpenes is not None else None,
            Jsonb(record.terpenes_std) if record.terpenes_std is not None else None,
            record.terp_total,
            Jsonb(record.cannabinoids_std) if record.cannabinoids_std is not None else None,
            Jsonb(record.variants) if record.variants is not None else None,
            now,
        ),
    )


def count_store_products(conn: DBConn, store_key: str) -> int:
    """How many product rows are currently stored for one store."""
    row = conn.execute(
        "SELECT COUNT(*) FROM store_products WHERE store_key = %s", (store_key,)
    ).fetchone()
    return row[0] if row else 0


# A re-scrape that collapses to a small fraction of the stored snapshot is almost always a
# throttled PARTIAL fetch — the aggregator 406 soft-block truncates a menu mid-pagination and
# tends to drive a store to near-zero
# — not a genuine menu shrink. Keep the larger prior rather than overwrite it with a fragment,
# the way Stage-2 stores have keep-the-best. The guard only holds while the prior is still FRESH:
# a real shrink (or a store that truly lost most of its menu) still lands once the old snapshot
# ages past the window, so a store can never be wedged on stale data forever.
_MENU_RETAIN_FRACTION = 0.5
_MENU_RETAIN_MAX_AGE_HOURS = 48.0


def _snapshot_age_hours(conn: DBConn, store_key: str) -> float | None:
    """Hours since this store's current snapshot was taken, or None if it has none."""
    # Cast to timestamptz so the max is chronological, not a lexical string max — and so psycopg
    # returns a tz-aware datetime, removing the naive-timestamp parse this used to guard against.
    row = conn.execute(
        "SELECT max(scraped_at::timestamptz) FROM store_products WHERE store_key = %s",
        (store_key,),
    ).fetchone()
    if row is None or row[0] is None:
        return None
    return (datetime.datetime.now(datetime.UTC) - row[0]).total_seconds() / 3600.0


def replace_store_products(
    conn: DBConn, store_key: str, records: list[StoreProductRecord]
) -> int:
    """Replace one store's menu snapshot wholesale. Caller commits.

    Menus churn daily, so a complete re-scrape is the new truth — but two cases are
    guarded so a bad scrape can't destroy a good snapshot:

    - an EMPTY result keeps the prior snapshot (a transient fetch failure must not
      wipe a good menu);
    - a result that collapses to under ``_MENU_RETAIN_FRACTION`` of a still-fresh
      prior (younger than ``_MENU_RETAIN_MAX_AGE_HOURS``) is treated as a throttled
      PARTIAL fetch and rejected — a 406-truncated fragment must not overwrite a full
      snapshot. Once the prior ages out of the window a genuine shrink still lands.

    Returns the resulting product count (the kept prior count when a guard fires).
    """
    if not records:
        return count_store_products(conn, store_key)
    prior = count_store_products(conn, store_key)
    if prior and len(records) < prior * _MENU_RETAIN_FRACTION:
        age_hours = _snapshot_age_hours(conn, store_key)
        if age_hours is not None and age_hours < _MENU_RETAIN_MAX_AGE_HOURS:
            print(
                f"  store_menu: {store_key} kept prior {prior} products "
                f"(re-scrape yielded {len(records)} < {_MENU_RETAIN_FRACTION:.0%} of "
                f"a {age_hours:.0f}h-old snapshot — likely a throttled partial)"
            )
            return prior
    conn.execute("DELETE FROM store_products WHERE store_key = %s", (store_key,))
    for record in records:
        insert_store_product(conn, record)
    return len(records)


# Categories whose products feed the master-DB observation history. Widened from flower-only to every
# CONSUMABLE category (those carrying price/potency/terpene/cannabinoid signal worth a time series);
# Accessory / Other / uncategorized are excluded (gear + grab-bag, no chemistry). For mg-dosed
# categories (edibles/tinctures/beverages/capsules) the dose is folded into product_fingerprint
# (thc_mg/cbd_mg), so a 10mg vs 100mg gummy of the same name are distinct identities.
_OBSERVED_CATEGORIES = (
    "Flower", "Pre-Roll", "Vape", "Concentrate", "Edible",
    "Beverage", "Tincture", "Topical", "Capsule",
)


def _observation_changed(prev: tuple, record: StoreProductRecord) -> bool:
    """Whether a record's price/potency/terpenes/cannabinoids differ from the last observation ``prev``
    = (product_id, price, thc, cbd, thc_mg, cbd_mg, terp_total, terpenes_std, cannabinoids_std, date)."""
    return (
        prev[1] != record.price or prev[2] != record.thc or prev[3] != record.cbd
        or prev[4] != record.thc_mg or prev[5] != record.cbd_mg or prev[6] != record.terp_total
        or (prev[7] or None) != (record.terpenes_std or None)
        or (prev[8] or None) != (record.cannabinoids_std or None)
    )


def record_observations(
    conn: DBConn, store_key: str, records: list[StoreProductRecord],
    *, now: datetime.datetime | None = None,
) -> int:
    """Append price/potency/terpene history for a store's observed-category products. Caller commits.

    The master-DB write path, run alongside the snapshot replace:
    upsert each product's identity into ``products``, then APPEND a ``product_observations`` row when
    its price/potency/terpenes changed since the last observation at this store, or once a day as a
    presence heartbeat. Append-only — rows are never updated or deleted. Scoped to consumable
    categories (``_OBSERVED_CATEGORIES``). ``now`` (the observation timestamp) defaults to the current UTC time;
    it is injectable for tests. Returns the number of observation rows appended.
    """
    observed_at = now or datetime.datetime.now(datetime.UTC)
    by_fp: dict[str, StoreProductRecord] = {}
    for record in records:
        if record.category_std not in _OBSERVED_CATEGORIES:
            continue
        fingerprint = text.product_fingerprint(
            record.brand, record.name, record.size_g, record.product_type_std,
            thc_mg=record.thc_mg, cbd_mg=record.cbd_mg,
        )
        if fingerprint:
            by_fp[fingerprint] = record  # a menu may list one product twice — keep the last
    if not by_fp:
        return 0

    # Upsert product identities → fingerprint:id (first_seen kept; last_seen bumped on re-sight).
    fp_to_id: dict[str, int] = {}
    for fingerprint, record in by_fp.items():
        row = conn.execute(
            "INSERT INTO products (fingerprint, brand, name, category_std, product_type_std, "
            "strain_type_std, size_g) VALUES (%s, %s, %s, %s, %s, %s, %s) "
            "ON CONFLICT (fingerprint) DO UPDATE SET last_seen = now() RETURNING id",
            (fingerprint, text.normalize_brand(record.brand or ""), record.name,
             record.category_std, record.product_type_std, record.strain_type_std, record.size_g),
        ).fetchone()
        assert row is not None  # INSERT ... RETURNING always yields a row
        fp_to_id[fingerprint] = row[0]

    # The last observation per product at this store, for change detection.
    last: dict[int, tuple] = {}
    for row in conn.execute(
        "SELECT DISTINCT ON (product_id) product_id, price, thc, cbd, thc_mg, cbd_mg, terp_total, "
        "terpenes_std, cannabinoids_std, scraped_at::date FROM product_observations "
        "WHERE store_key = %s AND product_id = ANY(%s) ORDER BY product_id, scraped_at DESC",
        (store_key, list(fp_to_id.values())),
    ):
        last[row[0]] = row

    appended = 0
    for fingerprint, record in by_fp.items():
        product_id = fp_to_id[fingerprint]
        prev = last.get(product_id)
        same_day = prev is not None and prev[9] == observed_at.date()
        if prev is not None and same_day and not _observation_changed(prev, record):
            continue  # already have today's row and nothing changed — no duplicate heartbeat
        conn.execute(
            "INSERT INTO product_observations (product_id, store_key, state, price, thc, cbd, "
            "thc_mg, cbd_mg, terpenes_std, terp_total, cannabinoids_std, scraped_at) "
            "VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)",
            (product_id, store_key, record.state, record.price, record.thc, record.cbd,
             record.thc_mg, record.cbd_mg,
             Jsonb(record.terpenes_std) if record.terpenes_std is not None else None,
             record.terp_total,
             Jsonb(record.cannabinoids_std) if record.cannabinoids_std is not None else None,
             observed_at),
        )
        appended += 1
    return appended


# ── store-lifecycle history primitives (orchestrated in the overlay, which owns the location_key
#    computation since the key builders live in sources/dedupe.py — see docs/store_history_design.md) ──

def get_company_store_rows(
    conn: DBConn, company_id: int, state: str
) -> list[tuple]:
    """The company's current stored rows (canonical + alias), for a store-observation pass.

    Returns ``(canonical_name, storefront_name, address, city, zip_code, latitude, longitude,
    platform, external_id)`` per row — the fields a store observation records."""
    return conn.execute(
        "SELECT canonical_name, storefront_name, address, city, zip_code, latitude, longitude, "
        "platform, external_id FROM company_stores WHERE company_id = %s AND state = %s",
        (company_id, state),
    ).fetchall()


def upsert_store_location(
    conn: DBConn, *, location_key: str, state: str, latitude: float | None,
    longitude: float | None, address: str | None, city: str | None, zip_code: str | None,
) -> int:
    """Upsert a physical-location identity, returning its id. Keeps ``first_seen``, bumps
    ``last_seen`` and refreshes the representative attrs on re-sight. Caller commits."""
    row = conn.execute(
        "INSERT INTO store_locations (location_key, state, latitude, longitude, address, city, "
        "zip_code) VALUES (%s, %s, %s, %s, %s, %s, %s) "
        "ON CONFLICT (location_key) DO UPDATE SET last_seen = now(), state = EXCLUDED.state, "
        "latitude = EXCLUDED.latitude, longitude = EXCLUDED.longitude, address = EXCLUDED.address, "
        "city = EXCLUDED.city, zip_code = EXCLUDED.zip_code RETURNING id",
        (location_key, state, latitude, longitude, address, city, zip_code),
    ).fetchone()
    assert row is not None  # INSERT ... RETURNING always yields a row
    return row[0]


def latest_store_observations(
    conn: DBConn, location_ids: list[int], source: str
) -> dict[int, tuple]:
    """The most recent observation per location for a source, for change detection. Returns
    ``location_id -> (operator, storefront_name, platform, external_id, address, city,
    observed_at::date)``."""
    if not location_ids:
        return {}
    rows = conn.execute(
        "SELECT DISTINCT ON (location_id) location_id, operator, storefront_name, platform, "
        "external_id, address, city, observed_at::date FROM store_observations "
        "WHERE source = %s AND location_id = ANY(%s) ORDER BY location_id, observed_at DESC",
        (source, location_ids),
    ).fetchall()
    return {row[0]: row[1:] for row in rows}


def append_store_observation(
    conn: DBConn, *, location_id: int, source: str, operator: str | None,
    storefront_name: str | None, platform: str | None, external_id: str | None,
    address: str | None, city: str | None, observed_at: datetime.datetime,
) -> None:
    """Append one append-only store observation. Caller commits."""
    conn.execute(
        "INSERT INTO store_observations (location_id, source, operator, storefront_name, platform, "
        "external_id, address, city, observed_at) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)",
        (location_id, source, operator, storefront_name, platform, external_id, address, city,
         observed_at),
    )


def record_location_observations(
    conn: DBConn, source: str, observations: dict[str, LocationObservation],
    *, now: datetime.datetime | None = None,
) -> int:
    """The shared store-lifecycle write engine: upsert identities, append what changed. Caller commits.

    ``observations`` is one :class:`LocationObservation` per ``location_key`` — the caller computes
    the keys (``dedupe`` lives above ``db`` in the layering) and collapses same-rooftop duplicates
    with its own preference rule. For each: upsert the identity into ``store_locations``
    (keep ``first_seen``), then APPEND a ``store_observations`` row when the observed
    operator/storefront/handle/address changed since the last observation for this
    ``(location, source)``, or once a day as a presence heartbeat. Append-only; both the Stage-2
    ``company_site`` and Stage-1 ``state_roster`` captures drive this one engine
    (docs/store_history_design.md). Returns the number of observation rows appended.
    """
    if not observations:
        return 0
    observed_at = now or datetime.datetime.now(datetime.UTC)
    by_location: dict[int, LocationObservation] = {}
    for location_key, obs in observations.items():
        location_id = upsert_store_location(
            conn, location_key=location_key, state=obs.state, latitude=obs.latitude,
            longitude=obs.longitude, address=obs.address, city=obs.city, zip_code=obs.zip_code,
        )
        by_location[location_id] = obs

    last = latest_store_observations(conn, list(by_location), source)
    appended = 0
    for location_id, obs in by_location.items():
        observed = (obs.operator, obs.storefront_name, obs.platform, obs.external_id,
                    obs.address, obs.city)
        prev = last.get(location_id)  # (operator, storefront, platform, external_id, address, city, date)
        same_day = prev is not None and prev[6] == observed_at.date()
        if prev is not None and same_day and prev[:6] == observed:
            continue  # already have today's row and nothing changed — no duplicate heartbeat
        append_store_observation(
            conn, location_id=location_id, source=source, operator=obs.operator,
            storefront_name=obs.storefront_name, platform=obs.platform,
            external_id=obs.external_id, address=obs.address, city=obs.city,
            observed_at=observed_at,
        )
        appended += 1
    return appended


# The "kept menu-bearing store per handle" selector — only canonical rows
# (``canonical_company_id IS NULL``) that carry a Stage-3 scrape handle (``platform`` + a non-empty
# ``external_id``). Shared by :func:`get_menu_stores_for_state` (the row Stage 3 scrapes under) and
# :func:`realign_store_products_company` (the row a snapshot is re-filed under) so both resolve the
# SAME row per ``(platform, external_id)`` — a filter/tiebreak edit here can't drift them apart.
# Callers supply their own SELECT-list, the ``state = %s`` filter, and ``DISTINCT ON (platform,
# external_id)``.
_KEPT_HANDLE_WHERE = (
    "canonical_company_id IS NULL "
    "AND platform IS NOT NULL AND external_id IS NOT NULL AND external_id != ''"
)
_KEPT_HANDLE_ORDER = "ORDER BY platform, external_id, company_id"


# The "natural flower" filter for product analyses (potency forensics, chemovar clustering): the
# Flower category MINUS adulterated/enhanced bud — flower sprayed or coated with added cannabinoids
# (so its potency/terpenes aren't the plant's own fingerprint). Excludes the `Infused` product type
# plus the name-tells the taxonomy misses (moonrock, kief-/dusted-/coated-/covered-). "diamond" and
# "caviar" are deliberately NOT excluded — they're mostly legitimate strain names with normal THC,
# not adulteration. A WHERE fragment over `store_products`; callers add their own SELECT-list/filters.
NATURAL_FLOWER_WHERE = (
    "category_std = 'Flower' AND product_type_std IS DISTINCT FROM 'Infused' "
    "AND coalesce(name, '') !~* '(infus|moonrock|moon rock|kief|dusted|coated|covered)'"
)



def get_menu_stores_for_state(conn: DBConn, abbr: str) -> list[tuple]:
    """Stores in a state that carry a Stage-3 menu handle, one row per store.

    Returns (company_id, canonical_name, source, platform, external_id, store_url,
    name, address, city) — ``source`` (the Stage-2 discovery rung) says which
    platform the external_id belongs to, which is what menu routing keys on;
    ``platform`` is the recon hint; address/city let a rung re-resolve a dubious
    captured id against a platform directory. Only canonical rows (shared-brand
    duplicates point at the same physical store) and only stores whose scrape
    stamped a platform + external_id; DISTINCT ON the handle so two operators
    sharing a storefront yield one menu job.
    """
    return conn.execute(
        "SELECT DISTINCT ON (platform, external_id) "
        "company_id, canonical_name, source, platform, external_id, store_url, name, "
        "address, city "
        "FROM company_stores "
        f"WHERE state = %s AND {_KEPT_HANDLE_WHERE} "
        f"{_KEPT_HANDLE_ORDER}",
        (abbr,),
    ).fetchall()


def latest_snapshot_times(conn: DBConn, abbr: str) -> dict[str, datetime.datetime]:
    """Most recent snapshot time per ``store_key`` for a state's menu snapshots.

    Drives Stage-3 freshness gating: a store whose latest snapshot is younger than
    the refresh window is skipped on the next run. ``scraped_at`` is cast to timestamptz so
    the max is chronological (not a lexical string max) and the values come back as tz-aware
    datetimes the caller compares directly — no string parsing.
    """
    rows = conn.execute(
        "SELECT store_key, max(scraped_at::timestamptz) FROM store_products "
        "WHERE state = %s GROUP BY store_key",
        (abbr,),
    ).fetchall()
    return dict(rows)


def get_recon_companies_for_state(
    conn: DBConn, abbr: str
) -> list[tuple[int, str, str, str | None]]:
    """Return (company_id, canonical_name, homepage_url, platform) for a state.

    Every recon'd company is returned, with ``homepage_url`` coalesced to ``''`` when the
    probe found no site. Companies with a homepage run the full own-site ladder; the
    homeless ones (``homepage == ''``) still get the homepage-INDEPENDENT Dutchie geo-sweep
    rung (it attributes by ``chain`` from the shared state pool), so a Dutchie operator is
    discoverable without seeding its homepage — see ``_company_catalog``.
    """
    return conn.execute(
        "SELECT cr.company_id, cr.canonical_name, COALESCE(cr.homepage_url, ''), cr.platform "
        "FROM company_recon cr JOIN companies c ON c.id = cr.company_id "
        "WHERE c.state = %s "
        "ORDER BY cr.canonical_name",
        (abbr,),
    ).fetchall()


def get_company_stores_for_dedupe(conn: DBConn, abbr: str) -> list[tuple]:
    """Return (id, company_id, canonical_name, name, address, city, zip_code,
    latitude, longitude, platform, external_id) rows — coordinates feed dedupe's
    geo-fallback key; platform + external_id let it keep the richest-menu handle per
    physical store (so a Dutchie/first-party store isn't demoted to its aggregator twin)."""
    return conn.execute(
        "SELECT id, company_id, canonical_name, name, address, city, zip_code, "
        "latitude, longitude, platform, external_id FROM company_stores "
        "WHERE state = %s ORDER BY id",
        (abbr,),
    ).fetchall()


def clear_store_canonical_for_state(conn: DBConn, abbr: str) -> None:
    """Reset all dedupe markers in a state so a fresh dedupe pass can re-decide."""
    conn.execute(
        "UPDATE company_stores SET canonical_company_id = NULL WHERE state = %s",
        (abbr,),
    )


def set_store_canonical(conn: DBConn, store_id: int, canonical_company_id: int) -> None:
    """Mark one company_store row as a duplicate of an operator's canonical company."""
    conn.execute(
        "UPDATE company_stores SET canonical_company_id = %s WHERE id = %s",
        (canonical_company_id, store_id),
    )


def realign_store_products_company(conn: DBConn, abbr: str) -> int:
    """Re-point a state's menu snapshots at the CURRENT kept company row for each handle.

    A snapshot is stamped with the company_id that owned its ``(platform, external_id)`` handle
    when it was scraped. A later dedupe can move the kept (canonical) row to a different company
    of the same operator cluster — Sunnyside's PA stores were scraped under the "Delta 9
    Pittsburgh" alias, then dedupe made "Sunnyside" canonical — but the snapshots keep the stale
    id, so per-operator menu reporting mis-attributes them. This re-stamps every snapshot to the
    company of the current kept row (``canonical_company_id IS NULL``, DISTINCT ON the handle),
    which is exactly the row :func:`get_menu_stores_for_state` scrapes under, so a snapshot is
    always filed under the same company a fresh scrape would use. Idempotent; returns rows moved.

    Handle-scoped: re-attribution keys on ``(platform, external_id)``, so a snapshot whose OWN
    handle was the folded (non-kept) side of a cross-handle merge maps to no kept row and keeps its
    prior company_id — a rare residual (one rooftop menu-scraped under two distinct handles, then
    folded; the folded row still exists, so the snapshot is not an orphan the menu-prune would catch).
    """
    cur = conn.execute(
        "UPDATE store_products sp SET company_id = k.company_id "
        "FROM (SELECT DISTINCT ON (platform, external_id) platform, external_id, company_id "
        "      FROM company_stores "
        f"      WHERE state = %s AND {_KEPT_HANDLE_WHERE} "
        f"      {_KEPT_HANDLE_ORDER}) k "
        "WHERE sp.state = %s AND sp.platform = k.platform AND sp.external_id = k.external_id "
        "  AND sp.company_id <> k.company_id",
        (abbr, abbr),
    )
    return cur.rowcount


def set_store_storefront(conn: DBConn, store_id: int, storefront_name: str) -> None:
    """Stamp the storefront (display) brand onto one store. Caller commits."""
    conn.execute(
        "UPDATE company_stores SET storefront_name = %s WHERE id = %s",
        (storefront_name, store_id),
    )


def set_store_location(
    conn: DBConn,
    store_id: int,
    latitude: float,
    longitude: float,
    address: str | None,
    zip_code: str | None,
) -> None:
    """Carry a geocoded sibling's coordinates (and a backfilled address/zip) onto a kept store.

    Used by dedupe when the row that won the kept slot is an address-less handle duplicate but a
    folded sibling has coordinates — so the surviving row still plots on the maps. Caller commits."""
    conn.execute(
        "UPDATE company_stores SET latitude = %s, longitude = %s, address = %s, zip_code = %s "
        "WHERE id = %s",
        (latitude, longitude, address, zip_code, store_id),
    )


_UPSERT_ACCESS_METHOD = """
INSERT INTO access_methods
  (target_type, target_key, method, cost_rank, status, resource_url, params,
   record_count, error, attempts, last_ok_at, last_fail_at, updated_at)
VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,1,%s,%s,%s)
ON CONFLICT (target_type, target_key, method) DO UPDATE SET
  cost_rank    = excluded.cost_rank,
  status       = excluded.status,
  -- On success keep/refresh the winning locator; on FAILURE clear it, so the next
  -- attempt re-discovers instead of re-serving a now-broken URL (the stale-hint lock).
  resource_url = CASE WHEN excluded.status = 'ok'
                      THEN COALESCE(excluded.resource_url, access_methods.resource_url)
                      ELSE excluded.resource_url END,
  params       = CASE WHEN excluded.status = 'ok'
                      THEN COALESCE(excluded.params, access_methods.params)
                      ELSE excluded.params END,
  record_count = excluded.record_count,
  error        = excluded.error,
  attempts     = access_methods.attempts + 1,
  last_ok_at   = CASE WHEN excluded.status = 'ok'
                      THEN excluded.updated_at ELSE access_methods.last_ok_at END,
  last_fail_at = CASE WHEN excluded.status = 'failed'
                      THEN excluded.updated_at ELSE access_methods.last_fail_at END,
  updated_at   = excluded.updated_at
"""

# Columns returned by the access_methods getters, in order.
ACCESS_METHOD_COLUMNS = (
    "method", "cost_rank", "status", "resource_url", "params",
    "record_count", "error", "attempts", "last_ok_at", "last_fail_at",
)


def record_access_attempt(
    conn: DBConn,
    target_type: str,
    target_key: str,
    method: str,
    cost_rank: int,
    status: str,
    resource_url: str | None = None,
    params: str | None = None,
    record_count: int | None = None,
    error: str | None = None,
) -> None:
    """Upsert the outcome of one method attempt against one target. Caller commits.

    On 'ok' the last_ok_at timestamp advances; on 'failed', last_fail_at. attempts
    increments on every call. A null resource_url/params preserves the stored value.
    """
    now = datetime.datetime.now(datetime.UTC).isoformat()
    ok_at = now if status == "ok" else None
    fail_at = now if status == "failed" else None
    conn.execute(
        _UPSERT_ACCESS_METHOD,
        (
            target_type, target_key, method, cost_rank, status, resource_url,
            params, record_count, error, ok_at, fail_at, now,
        ),
    )


def get_access_methods(conn: DBConn, target_type: str, target_key: str) -> list[tuple]:
    """Return all recorded method rows for a target (see ACCESS_METHOD_COLUMNS)."""
    return conn.execute(
        "SELECT method, cost_rank, status, resource_url, params, record_count, "
        "error, attempts, last_ok_at, last_fail_at FROM access_methods "
        "WHERE target_type = %s AND target_key = %s ORDER BY cost_rank",
        (target_type, target_key),
    ).fetchall()


def get_access_winner(
    conn: DBConn, target_type: str, target_key: str
) -> tuple | None:
    """Return the cheapest 'ok' method row for a target, or None (see columns)."""
    return conn.execute(
        "SELECT method, cost_rank, status, resource_url, params, record_count, "
        "error, attempts, last_ok_at, last_fail_at FROM access_methods "
        "WHERE target_type = %s AND target_key = %s AND status = 'ok' "
        "ORDER BY cost_rank LIMIT 1",
        (target_type, target_key),
    ).fetchone()


_CREATE_STATE_PROGRAMS = """
CREATE TABLE IF NOT EXISTS state_programs (
    abbr         TEXT PRIMARY KEY,
    name         TEXT NOT NULL,
    programs     TEXT NOT NULL,
    program_term TEXT,
    agency       TEXT,
    best_url     TEXT,
    source_type  TEXT,
    all_gov_urls TEXT,
    last_checked TEXT,
    check_status TEXT NOT NULL DEFAULT 'never',
    searched_at  TEXT,
    error        TEXT,
    list_url      TEXT,
    list_type     TEXT,
    list_found_at TEXT,
    list_status   TEXT
)
"""

# Columns added after the original state_programs schema shipped. create_tables()
# adds any that are missing so existing databases upgrade in place.
_STATE_PROGRAM_ADDED_COLUMNS = {
    "list_url": "TEXT",
    "list_type": "TEXT",
    "list_found_at": "TEXT",
    "list_status": "TEXT",
}

_UPSERT_STATE_PROGRAM = """
INSERT INTO state_programs
  (abbr, name, programs, program_term, agency, best_url, source_type,
   all_gov_urls, last_checked, check_status, searched_at, error)
VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
ON CONFLICT (abbr) DO UPDATE SET
  best_url     = excluded.best_url,
  source_type  = excluded.source_type,
  all_gov_urls = excluded.all_gov_urls,
  last_checked = excluded.last_checked,
  check_status = excluded.check_status,
  searched_at  = excluded.searched_at,
  error        = excluded.error
"""


def upsert_state_program(conn: DBConn, record: StateProgramRecord) -> None:
    """Upsert one StateProgramRecord. Caller must commit."""
    conn.execute(
        _UPSERT_STATE_PROGRAM,
        (
            record.abbr,
            record.name,
            record.programs,
            record.program_term,
            record.agency,
            record.best_url,
            record.source_type,
            json.dumps(record.all_gov_urls),
            record.last_checked,
            record.check_status,
            record.searched_at,
            record.error,
        ),
    )


def get_state_program(conn: DBConn, abbr: str) -> StateProgramRecord | None:
    """Return the stored StateProgramRecord for a state, or None."""
    row = conn.execute(
        "SELECT abbr, name, programs, program_term, agency, best_url, source_type, "
        "all_gov_urls, last_checked, check_status, searched_at, error, "
        "list_url, list_type, list_found_at, list_status "
        "FROM state_programs WHERE abbr = %s",
        (abbr,),
    ).fetchone()
    if row is None:
        return None
    return _row_to_state_program(row)


def get_all_state_programs(conn: DBConn) -> list[StateProgramRecord]:
    """Return all stored StateProgramRecords ordered by state name."""
    rows = conn.execute(
        "SELECT abbr, name, programs, program_term, agency, best_url, source_type, "
        "all_gov_urls, last_checked, check_status, searched_at, error, "
        "list_url, list_type, list_found_at, list_status "
        "FROM state_programs ORDER BY name"
    ).fetchall()
    return [_row_to_state_program(row) for row in rows]


def _row_to_state_program(row: tuple) -> StateProgramRecord:
    abbr, name, programs, program_term, agency, best_url, source_type, \
        all_gov_urls_json, last_checked, check_status, searched_at, error, \
        list_url, list_type, list_found_at, list_status = row
    all_gov_urls: list[str] = []
    if all_gov_urls_json:
        with contextlib.suppress(ValueError, TypeError):
            all_gov_urls = json.loads(all_gov_urls_json)
    return StateProgramRecord(
        abbr=abbr,
        name=name,
        programs=programs,
        program_term=program_term or "",
        agency=agency or "",
        best_url=best_url,
        source_type=source_type,
        all_gov_urls=all_gov_urls,
        last_checked=last_checked,
        check_status=check_status or "never",
        searched_at=searched_at,
        error=error,
        list_url=list_url,
        list_type=list_type,
        list_found_at=list_found_at,
        list_status=list_status,
    )


def set_state_list(
    conn: DBConn,
    abbr: str,
    list_url: str | None,
    list_type: str | None,
    list_status: str,
) -> None:
    """Update only the dispensary-list columns for a state. Caller must commit.

    Kept separate from upsert_state_program so the search/verify flow (which builds
    records without list data) never clobbers a discovered list URL.
    """
    now = datetime.datetime.now(datetime.UTC).isoformat()
    conn.execute(
        "UPDATE state_programs "
        "SET list_url = %s, list_type = %s, list_found_at = %s, list_status = %s "
        "WHERE abbr = %s",
        (list_url, list_type, now, list_status, abbr),
    )


def delete_dispensaries_for_state(conn: DBConn, abbr: str) -> int:
    """Delete all dispensary rows for a state so a re-scrape replaces them.

    Returns the number of rows deleted; caller must commit.
    """
    cur = conn.execute("DELETE FROM dispensaries WHERE state = %s", (abbr,))
    return cur.rowcount
