import datetime
import os
from typing import TYPE_CHECKING, Any, LiteralString

import psycopg

if TYPE_CHECKING:  # real signatures for the reference API that __getattr__ delegates (no runtime import,
    # so the engine stays cannabis-free); keeps LiteralString-typed constants like NATURAL_FLOWER_WHERE
    # inferring correctly at db.* call sites. Retire when callers re-point to rung.reference_db (B5).
    from rung.reference_db import (  # noqa: F401
        NATURAL_FLOWER_WHERE,
        append_store_observation,
        clear_store_canonical_for_state,
        count_company_stores,
        count_store_products,
        create_reference_tables,
        create_tables,
        delete_company_stores_for_company,
        delete_dispensaries_for_state,
        get_all_state_programs,
        get_company_store_rows,
        get_company_stores_for_dedupe,
        get_menu_stores_for_state,
        get_recon_companies_for_state,
        get_state_program,
        insert_company_store,
        insert_dispensary,
        insert_store_product,
        latest_snapshot_times,
        latest_store_observations,
        realign_store_products_company,
        record_location_observations,
        record_observations,
        replace_company_stores,
        replace_store_products,
        set_state_list,
        set_store_canonical,
        set_store_location,
        set_store_storefront,
        upsert_recon,
        upsert_state_program,
    )

type DBConn = psycopg.Connection

_DEFAULT_DATABASE_URL = "postgresql://rung:rung@localhost:5432/rung"

_CREATE_ACCESS_METHODS = """
CREATE TABLE IF NOT EXISTS access_methods (
    target_type  TEXT    NOT NULL,
    target_key   TEXT    NOT NULL,
    method       TEXT    NOT NULL,
    cost_rank    INTEGER NOT NULL,
    status       TEXT    NOT NULL DEFAULT 'never',
    resource_url TEXT,
    params       TEXT,
    record_count INTEGER,
    error        TEXT,
    attempts     INTEGER NOT NULL DEFAULT 0,
    last_ok_at   TEXT,
    last_fail_at TEXT,
    updated_at   TEXT    NOT NULL,
    PRIMARY KEY (target_type, target_key, method)
)
"""

# Transient per-run work items (claims close the documented concurrency hazards —
# see docs/stage_contracts.md §5). Companion to access_methods, which is the
# DURABLE per-target memory; jobs rows are run bookkeeping. timestamptz here
# (unlike the TEXT timestamps elsewhere) because the requeue-timeout math runs in SQL.
_CREATE_JOBS = """
CREATE TABLE IF NOT EXISTS jobs (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_type    TEXT NOT NULL,
    target_key   TEXT NOT NULL,
    payload      JSONB,
    status       TEXT NOT NULL DEFAULT 'pending',
    attempts     INTEGER NOT NULL DEFAULT 0,
    max_attempts INTEGER NOT NULL DEFAULT 3,
    claimed_by   TEXT,
    claimed_at   TIMESTAMPTZ,
    scheduled_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at  TIMESTAMPTZ,
    error        TEXT
)
"""

# Dedupes LIVE jobs per (task_type, target_key) while letting done/failed rows
# accumulate as run history. Also indexes the claim predicate.
_CREATE_JOBS_LIVE_UNIQUE = """
CREATE UNIQUE INDEX IF NOT EXISTS jobs_live_unique
    ON jobs (task_type, target_key) WHERE status IN ('pending', 'claimed')
"""

# Partial index over just the CLAIMABLE rows, matching the claim scan's shape
# (WHERE task_type=… AND status='pending' AND scheduled_at<=now() ORDER BY id LIMIT 1). As
# done/failed history accumulates between prunes the live-unique index above still spans every
# status; this one covers only pending rows so the FOR UPDATE SKIP LOCKED claim stays an
# index-only scan of the tiny working set. See docs/distributed_scraping_design.md §4-5.
_CREATE_JOBS_PENDING_CLAIM = """
CREATE INDEX IF NOT EXISTS jobs_pending_claim ON jobs (task_type, id) WHERE status = 'pending'
"""

# jobs columns added after the table's first release — applied in-place by _migrate_jobs so an
# existing database picks them up. lease/heartbeat back the distributed-worker lease + SKIP-LOCKED
# reaper (queue.reap_expired / bump_heartbeat); see docs/distributed_scraping_design.md §4-5. A
# claim stamps both; a long-running worker bumps last_heartbeat/lease_until; the reaper re-queues a
# claim whose lease_until has passed (a crashed/hung worker), so a dead worker no longer wedges a job.
_JOBS_ADDED_COLUMNS = {
    "lease_until": "TIMESTAMPTZ",
    "last_heartbeat": "TIMESTAMPTZ",
}

# Durable cross-worker proxy health, keyed per (proxy_url × host) — a proxy can be fine on Dutchie
# but banned on Weedmaps, so health is tracked per host. Public infra (the DDL); the selection/health
# POLICY (claim the healthiest, disable after N consecutive fails + cooldown) is private
# (rung_intel.proxy_store). See docs/distributed_scraping_design.md §2.1/§3.
_CREATE_PROXIES = """
CREATE TABLE IF NOT EXISTS proxies (
    proxy_url         TEXT    NOT NULL,
    host              TEXT    NOT NULL,
    success_count     INTEGER NOT NULL DEFAULT 0,
    error_count       INTEGER NOT NULL DEFAULT 0,
    consecutive_fails INTEGER NOT NULL DEFAULT 0,
    disabled_until    TIMESTAMPTZ,
    last_used_at      TIMESTAMPTZ,
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (proxy_url, host)
)
"""
# The claim scan picks the healthiest non-disabled proxy for a host (order by consecutive_fails,
# last_used_at). Partial over the not-disabled fast path (the common case) so the scan is index-only.
_CREATE_PROXIES_CLAIM_INDEX = """
CREATE INDEX IF NOT EXISTS proxies_host_health ON proxies (host, consecutive_fails, last_used_at)
    WHERE disabled_until IS NULL
"""

# Per-platform egress-tier registry. One row per menu/store platform recording which proxy tier
# (direct/datacenter/residential) it should scrape through, the escalation-gate block rate that
# decided it, and where the decision came from. Public infra (the DDL, like `proxies`); the
# selection POLICY (config default + this override) is private (rung_intel.proxy_tiers).
# See docs/distributed_scraping_design.md §0 (escalation gate) / §1 (tiers).
_CREATE_PROXY_TIERS = """
CREATE TABLE IF NOT EXISTS proxy_tiers (
    platform        TEXT PRIMARY KEY,
    tier            TEXT NOT NULL,
    block_rate_pct  DOUBLE PRECISION,
    source          TEXT,
    decided_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
)
"""

# Cross-worker per-host rate limiter (token bucket). One row per host: `tokens` is the current
# allowance, refilled at `rate_per_sec` up to `burst` on each access using `now() - last_refill` as
# the elapsed clock. Public infra (like `jobs`); the refill/deduct policy lives in `rate_limit.py`
# and the aggregator-path integration is private (overlay). See docs/distributed_scraping_design.md §3-4.
_CREATE_TOKEN_BUCKETS = """
CREATE TABLE IF NOT EXISTS token_buckets (
    host        TEXT PRIMARY KEY,
    tokens      DOUBLE PRECISION NOT NULL,
    last_refill TIMESTAMPTZ NOT NULL DEFAULT now()
)
"""

def get_connection() -> DBConn:
    """Open and return a connection to the dispensaries database.

    Reads DATABASE_URL from the environment (default: local dev Postgres container).
    """
    url = os.environ.get("DATABASE_URL", _DEFAULT_DATABASE_URL)
    try:
        return psycopg.connect(url)
    except psycopg.OperationalError as exc:
        raise psycopg.OperationalError(
            f"{exc} — is the dev Postgres running?"
        ) from exc


def one(conn: DBConn, query: LiteralString, params: tuple = ()) -> tuple:
    """Run a query expected to return exactly one row and return it (never None).

    For aggregate / ``RETURNING`` / single-row SELECTs where ``fetchone()`` is logically non-None.
    Centralizes the ``Row | None`` narrowing so callers (esp. analysis scripts) can subscript the
    result directly without a per-call ``assert``. Raises if the query yields no row.
    """
    row = conn.execute(query, params).fetchone()
    if row is None:
        raise LookupError("query returned no row")
    return row


def create_engine_tables(conn: DBConn) -> None:
    """Create the **generic engine** tables only — the domain-neutral infrastructure any pipeline
    needs: the ``jobs`` work queue, the ``access_methods`` registry, the ``token_buckets`` rate
    limiter, and the ``proxies``/``proxy_tiers`` egress pool. Creates **no** domain tables.

    This is the table-creation call for a *build-your-own-domain* plugin (see
    ``docs/build-your-own-domain.md``): call it, then create your own record tables with your own DDL.
    Idempotent (``IF NOT EXISTS``); commits.
    """
    conn.execute(_CREATE_ACCESS_METHODS)
    conn.execute(_CREATE_JOBS)
    conn.execute(_CREATE_JOBS_LIVE_UNIQUE)
    conn.execute(_CREATE_JOBS_PENDING_CLAIM)
    _migrate_jobs(conn)
    conn.execute(_CREATE_TOKEN_BUCKETS)
    conn.execute(_CREATE_PROXIES)
    conn.execute(_CREATE_PROXIES_CLAIM_INDEX)
    conn.execute(_CREATE_PROXY_TIERS)
    conn.commit()


def _migrate_jobs(conn: DBConn) -> None:
    """Add any jobs columns missing from an older database (the lease/heartbeat columns)."""
    for column, col_type in _JOBS_ADDED_COLUMNS.items():
        # DDL with hardcoded column/type from a module constant (see _migrate_company_stores).
        conn.execute(  # ty: ignore[no-matching-overload]
            f"ALTER TABLE jobs ADD COLUMN IF NOT EXISTS {column} {col_type}"
        )


_UPSERT_ACCESS_METHOD = """
INSERT INTO access_methods
  (target_type, target_key, method, cost_rank, status, resource_url, params,
   record_count, error, attempts, last_ok_at, last_fail_at, updated_at)
VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,1,%s,%s,%s)
ON CONFLICT (target_type, target_key, method) DO UPDATE SET
  cost_rank    = excluded.cost_rank,
  status       = excluded.status,
  -- On success keep/refresh the winning locator; on FAILURE clear it, so the next
  -- attempt re-discovers instead of re-serving a now-broken URL (the stale-hint lock).
  resource_url = CASE WHEN excluded.status = 'ok'
                      THEN COALESCE(excluded.resource_url, access_methods.resource_url)
                      ELSE excluded.resource_url END,
  params       = CASE WHEN excluded.status = 'ok'
                      THEN COALESCE(excluded.params, access_methods.params)
                      ELSE excluded.params END,
  record_count = excluded.record_count,
  error        = excluded.error,
  attempts     = access_methods.attempts + 1,
  last_ok_at   = CASE WHEN excluded.status = 'ok'
                      THEN excluded.updated_at ELSE access_methods.last_ok_at END,
  last_fail_at = CASE WHEN excluded.status = 'failed'
                      THEN excluded.updated_at ELSE access_methods.last_fail_at END,
  updated_at   = excluded.updated_at
"""

# Columns returned by the access_methods getters, in order.
ACCESS_METHOD_COLUMNS = (
    "method", "cost_rank", "status", "resource_url", "params",
    "record_count", "error", "attempts", "last_ok_at", "last_fail_at",
)


def record_access_attempt(
    conn: DBConn,
    target_type: str,
    target_key: str,
    method: str,
    cost_rank: int,
    status: str,
    resource_url: str | None = None,
    params: str | None = None,
    record_count: int | None = None,
    error: str | None = None,
) -> None:
    """Upsert the outcome of one method attempt against one target. Caller commits.

    On 'ok' the last_ok_at timestamp advances; on 'failed', last_fail_at. attempts
    increments on every call. A null resource_url/params preserves the stored value.
    """
    now = datetime.datetime.now(datetime.UTC).isoformat()
    ok_at = now if status == "ok" else None
    fail_at = now if status == "failed" else None
    conn.execute(
        _UPSERT_ACCESS_METHOD,
        (
            target_type, target_key, method, cost_rank, status, resource_url,
            params, record_count, error, ok_at, fail_at, now,
        ),
    )


def get_access_methods(conn: DBConn, target_type: str, target_key: str) -> list[tuple]:
    """Return all recorded method rows for a target (see ACCESS_METHOD_COLUMNS)."""
    return conn.execute(
        "SELECT method, cost_rank, status, resource_url, params, record_count, "
        "error, attempts, last_ok_at, last_fail_at FROM access_methods "
        "WHERE target_type = %s AND target_key = %s ORDER BY cost_rank",
        (target_type, target_key),
    ).fetchall()


def get_access_winner(
    conn: DBConn, target_type: str, target_key: str
) -> tuple | None:
    """Return the cheapest 'ok' method row for a target, or None (see columns)."""
    return conn.execute(
        "SELECT method, cost_rank, status, resource_url, params, record_count, "
        "error, attempts, last_ok_at, last_fail_at FROM access_methods "
        "WHERE target_type = %s AND target_key = %s AND status = 'ok' "
        "ORDER BY cost_rank LIMIT 1",
        (target_type, target_key),
    ).fetchone()




def __getattr__(name: str) -> Any:
    """Back-compat delegation: the cannabis reference schema + CRUD moved to ``rung.reference_db``
    (genericization B1/B3). ``from rung import db; db.insert_dispensary(...)`` still resolves — routed
    here lazily so importing the *engine* ``db`` (as ``queue``/``access`` do) loads no cannabis
    ``models``/``text``. Returns ``Any`` (PEP 562 idiom); re-point call sites to ``rung.reference_db``
    for full typing (B5). Prefer importing ``rung.reference_db`` directly in new code."""
    import rung.reference_db as _ref
    try:
        return getattr(_ref, name)
    except AttributeError:
        raise AttributeError(f"module 'rung.db' has no attribute {name!r}") from None
