import datetime
import os
from dataclasses import dataclass
from typing import TYPE_CHECKING, Any, LiteralString

import psycopg

if TYPE_CHECKING:  # real signatures for the reference API that __getattr__ delegates (no runtime import,
    # so the engine stays cannabis-free); keeps LiteralString-typed constants like NATURAL_FLOWER_WHERE
    # inferring correctly at db.* call sites. Retire when callers re-point to rung.reference_db (B5).
    from rung.reference_db import (  # noqa: F401
        CA_PROVINCES_SUBQUERY,
        NATURAL_FLOWER_WHERE,
        NATURAL_FLOWER_WHERE_NORMALIZED,
        US_EXCL_TERRITORIES_SUBQUERY,
        US_JURISDICTIONS_SUBQUERY,
        US_TERRITORIES,
        append_store_observation,
        clear_store_canonical_for_state,
        count_company_stores,
        count_store_products,
        create_reference_tables,
        create_tables,
        delete_company_stores_for_company,
        delete_dispensaries_for_state,
        get_all_state_programs,
        get_company_store_rows,
        get_company_stores_for_dedupe,
        get_menu_stores_for_state,
        get_recon_companies_for_state,
        get_state_program,
        insert_company_store,
        insert_dispensary,
        insert_store_product,
        latest_snapshot_times,
        latest_store_observations,
        realign_store_products_company,
        record_location_observations,
        record_observations,
        replace_company_stores,
        replace_lifecycle_events,
        replace_store_products,
        set_state_list,
        set_store_canonical,
        set_store_location,
        set_store_storefront,
        upsert_recon,
        upsert_state_program,
    )

type DBConn = psycopg.Connection

_DEFAULT_DATABASE_URL = "postgresql://rung:rung@localhost:5432/rung"

# `status` is the OUTCOME VOCABULARY, and the distinction it draws is the point. A ladder that cannot
# say "I can't get this" and "you may not have this" in different words will always say the latter,
# because it is the more comfortable sentence — and then a broken rung reads as a fact about the world.
# That has happened here three times (see docs/access_methods_design.md §"Outcomes"):
#
#   ok           the method returned plausible records
#   unavailable  the WORLD says no — this target has no data by this route, and never will
#   blocked      we were REFUSED — 403/429/captcha; the data exists, this egress cannot have it
#   broken       WE are wrong — a dead URL, a parse failure, missing config. Fix the rung.
#   failed       a rung returned nothing and did not say why. The honest default; never 'unavailable'.
#   never        no attempt recorded yet
#
# `broken` must be impossible to record as `unavailable`: only an explicit `access.Unavailable` signal
# from the runner produces it. Silence produces `failed`.
_CREATE_ACCESS_METHODS = """
CREATE TABLE IF NOT EXISTS access_methods (
    target_type  TEXT    NOT NULL,
    target_key   TEXT    NOT NULL,
    method       TEXT    NOT NULL,
    cost_rank    INTEGER NOT NULL,
    status       TEXT    NOT NULL DEFAULT 'never',
    resource_url TEXT,
    params       TEXT,
    record_count INTEGER,
    error        TEXT,
    attempts     INTEGER NOT NULL DEFAULT 0,
    last_ok_at   TEXT,
    last_fail_at TEXT,
    updated_at   TEXT    NOT NULL,
    PRIMARY KEY (target_type, target_key, method),
    CONSTRAINT access_methods_status_check
        CHECK (status IN ('ok', 'unavailable', 'blocked', 'broken', 'failed', 'never'))
)
"""

# The outcome vocabulary, as data. `access.py` owns the semantics; `db` owns the storage and refuses
# anything outside the set — a typo'd status is a silent lie about why a rung stopped working.
ACCESS_STATUSES = frozenset({"ok", "unavailable", "blocked", "broken", "failed", "never"})

# Transient per-run work items (claims close the documented concurrency hazards —
# see docs/stage_contracts.md §5). Companion to access_methods, which is the
# DURABLE per-target memory; jobs rows are run bookkeeping. timestamptz here
# (unlike the TEXT timestamps elsewhere) because the requeue-timeout math runs in SQL.
_CREATE_JOBS = """
CREATE TABLE IF NOT EXISTS jobs (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_type    TEXT NOT NULL,
    target_key   TEXT NOT NULL,
    payload      JSONB,
    status       TEXT NOT NULL DEFAULT 'pending',
    attempts     INTEGER NOT NULL DEFAULT 0,
    max_attempts INTEGER NOT NULL DEFAULT 3,
    claimed_by   TEXT,
    claimed_at   TIMESTAMPTZ,
    scheduled_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at  TIMESTAMPTZ,
    error        TEXT
)
"""

# Dedupes LIVE jobs per (task_type, target_key) while letting done/failed rows
# accumulate as run history. Also indexes the claim predicate.
_CREATE_JOBS_LIVE_UNIQUE = """
CREATE UNIQUE INDEX IF NOT EXISTS jobs_live_unique
    ON jobs (task_type, target_key) WHERE status IN ('pending', 'claimed')
"""

# Partial index over just the CLAIMABLE rows, matching the claim scan's shape
# (WHERE task_type=… AND status='pending' AND scheduled_at<=now() ORDER BY id LIMIT 1). As
# done/failed history accumulates between prunes the live-unique index above still spans every
# status; this one covers only pending rows so the FOR UPDATE SKIP LOCKED claim stays an
# index-only scan of the tiny working set. See docs/distributed_scraping_design.md §4-5.
_CREATE_JOBS_PENDING_CLAIM = """
CREATE INDEX IF NOT EXISTS jobs_pending_claim ON jobs (task_type, id) WHERE status = 'pending'
"""

# jobs columns added after the table's first release — applied in-place by _migrate_jobs so an
# existing database picks them up. lease/heartbeat back the distributed-worker lease + SKIP-LOCKED
# reaper (queue.reap_expired / bump_heartbeat); see docs/distributed_scraping_design.md §4-5. A
# claim stamps both; a long-running worker bumps last_heartbeat/lease_until; the reaper re-queues a
# claim whose lease_until has passed (a crashed/hung worker), so a dead worker no longer wedges a job.
_JOBS_ADDED_COLUMNS = {
    "lease_until": "TIMESTAMPTZ",
    "last_heartbeat": "TIMESTAMPTZ",
}

# Durable cross-worker proxy health, keyed per (proxy_url × host) — a proxy can be fine on Dutchie
# but banned on Weedmaps, so health is tracked per host. Public infra (the DDL); the selection/health
# POLICY (claim the healthiest, disable after N consecutive fails + cooldown) is private
# (rung_intel.proxy_store). See docs/distributed_scraping_design.md §2.1/§3.
_CREATE_PROXIES = """
CREATE TABLE IF NOT EXISTS proxies (
    proxy_url         TEXT    NOT NULL,
    host              TEXT    NOT NULL,
    success_count     INTEGER NOT NULL DEFAULT 0,
    error_count       INTEGER NOT NULL DEFAULT 0,
    consecutive_fails INTEGER NOT NULL DEFAULT 0,
    disabled_until    TIMESTAMPTZ,
    last_used_at      TIMESTAMPTZ,
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (proxy_url, host)
)
"""
# The claim scan picks the healthiest non-disabled proxy for a host (order by consecutive_fails,
# last_used_at). Partial over the not-disabled fast path (the common case) so the scan is index-only.
_CREATE_PROXIES_CLAIM_INDEX = """
CREATE INDEX IF NOT EXISTS proxies_host_health ON proxies (host, consecutive_fails, last_used_at)
    WHERE disabled_until IS NULL
"""

# Per-platform egress-tier registry. One row per menu/store platform recording which proxy tier
# (direct/datacenter/residential) it should scrape through, the escalation-gate block rate that
# decided it, and where the decision came from. Public infra (the DDL, like `proxies`); the
# selection POLICY (config default + this override) is private (rung_intel.proxy_tiers).
# See docs/distributed_scraping_design.md §0 (escalation gate) / §1 (tiers).
_CREATE_PROXY_TIERS = """
CREATE TABLE IF NOT EXISTS proxy_tiers (
    platform        TEXT PRIMARY KEY,
    tier            TEXT NOT NULL,
    block_rate_pct  DOUBLE PRECISION,
    source          TEXT,
    decided_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
)
"""

# Externally-sourced facts an analysis depends on but cannot derive from its own data — "brand X is
# owned by company Y", "state Z began retail sales in 2018-01". Such a fact is a *premise*, and a
# premise with no recorded source is unfalsifiable: a reader cannot check it without redoing the
# author's research.
#
# Each row is one subject–predicate–object triple carrying the evidence for itself: where it came
# from, the exact supporting text, and when it was retrieved. `retrieved_at` matters because sources
# change — a corporate brand list is true of a filing, not of the world forever.
#
# `confidence` is the attestor's own grading, not a probability: `verified` (a primary source states
# it), `reported` (a reputable secondary source), `inferred` (derived, and therefore attackable).
# Generic infra, like `jobs`: the engine stores provenance; a domain decides what facts need it.
@dataclass
class Attestation:
    """One externally-sourced fact, carrying the evidence for itself.

    A *premise* an analysis relies on but cannot derive from its own data — "brand X is owned by
    company Y". Recorded as a subject-predicate-object triple plus the source that supports it, so a
    reader can check the premise without repeating the author's research.

    Engine infrastructure, like ``jobs``: the vocabulary of subject types and predicates belongs to
    the domain, and the engine has no opinion about it. (Defined here rather than in ``models`` so
    importing the engine loads no domain module — see ``tests/test_import_layering.py``.)
    """

    subject_type: str                   # 'brand' | 'company' | 'state' | … (the domain's vocabulary)
    subject: str
    predicate: str                      # 'owned_by' | 'operates' | 'not_owned_by' | …
    object: str
    source_type: str                    # 'sec_filing' | 'press_release' | 'company_site' | 'trade_press'
    source_ref: str                     # a citable handle, e.g. "Acme FY2024 Form 10-K"
    retrieved_at: str                   # ISO-8601 date — sources change; a fact is true *of a source*
    source_url: str | None = None
    quote: str | None = None            # the exact supporting text, so the claim is checkable in place
    confidence: str = "reported"        # 'verified' (primary source) | 'reported' | 'inferred'
    notes: str | None = None


_CREATE_ATTESTATIONS = """
CREATE TABLE IF NOT EXISTS attestations (
    subject_type  TEXT NOT NULL,
    subject       TEXT NOT NULL,
    predicate     TEXT NOT NULL,
    object        TEXT NOT NULL,
    source_type   TEXT NOT NULL,
    source_ref    TEXT NOT NULL,
    source_url    TEXT,
    quote         TEXT,
    confidence    TEXT NOT NULL DEFAULT 'reported',
    retrieved_at  DATE NOT NULL,
    notes         TEXT,
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (subject_type, subject, predicate, object, source_ref),
    CONSTRAINT attestations_confidence_check
        CHECK (confidence IN ('verified', 'reported', 'inferred'))
)
"""

_CREATE_ATTESTATIONS_LOOKUP = """
CREATE INDEX IF NOT EXISTS attestations_subject_idx
    ON attestations (subject_type, lower(subject), predicate)
"""

# Cross-worker per-host rate limiter (token bucket). One row per host: `tokens` is the current
# allowance, refilled at `rate_per_sec` up to `burst` on each access using `now() - last_refill` as
# the elapsed clock. Public infra (like `jobs`); the refill/deduct policy lives in `rate_limit.py`
# and the aggregator-path integration is private (overlay). See docs/distributed_scraping_design.md §3-4.
_CREATE_TOKEN_BUCKETS = """
CREATE TABLE IF NOT EXISTS token_buckets (
    host        TEXT PRIMARY KEY,
    tokens      DOUBLE PRECISION NOT NULL,
    last_refill TIMESTAMPTZ NOT NULL DEFAULT now()
)
"""

def get_connection() -> DBConn:
    """Open and return a connection to the dispensaries database.

    Reads DATABASE_URL from the environment (default: local dev Postgres container).
    """
    url = os.environ.get("DATABASE_URL", _DEFAULT_DATABASE_URL)
    try:
        return psycopg.connect(url)
    except psycopg.OperationalError as exc:
        raise psycopg.OperationalError(
            f"{exc} — is the dev Postgres running?"
        ) from exc


def one(conn: DBConn, query: LiteralString, params: tuple = ()) -> tuple:
    """Run a query expected to return exactly one row and return it (never None).

    For aggregate / ``RETURNING`` / single-row SELECTs where ``fetchone()`` is logically non-None.
    Centralizes the ``Row | None`` narrowing so callers (esp. analysis scripts) can subscript the
    result directly without a per-call ``assert``. Raises if the query yields no row.
    """
    row = conn.execute(query, params).fetchone()
    if row is None:
        raise LookupError("query returned no row")
    return row


def create_engine_tables(conn: DBConn) -> None:
    """Create the **generic engine** tables only — the domain-neutral infrastructure any pipeline
    needs: the ``jobs`` work queue, the ``access_methods`` registry, the ``token_buckets`` rate
    limiter, and the ``proxies``/``proxy_tiers`` egress pool. Creates **no** domain tables.

    This is the table-creation call for a *build-your-own-domain* plugin (see
    ``docs/build-your-own-domain.md``): call it, then create your own record tables with your own DDL.
    Idempotent (``IF NOT EXISTS``); commits.
    """
    conn.execute(_CREATE_ACCESS_METHODS)
    conn.execute(_CREATE_JOBS)
    conn.execute(_CREATE_JOBS_LIVE_UNIQUE)
    conn.execute(_CREATE_JOBS_PENDING_CLAIM)
    _migrate_jobs(conn)
    _migrate_access_methods(conn)
    conn.execute(_CREATE_TOKEN_BUCKETS)
    conn.execute(_CREATE_PROXIES)
    conn.execute(_CREATE_PROXIES_CLAIM_INDEX)
    conn.execute(_CREATE_PROXY_TIERS)
    conn.execute(_CREATE_ATTESTATIONS)
    conn.execute(_CREATE_ATTESTATIONS_LOOKUP)
    conn.commit()


def _migrate_access_methods(conn: DBConn) -> None:
    """Add the status CHECK to a database created before the outcome vocabulary existed.

    Safe on live data: production held only 'ok' and 'failed', both in the vocabulary. Postgres
    validates existing rows when the constraint is added, so a database carrying some other status
    fails loudly here rather than silently accepting it forever.
    """
    conn.execute(
        "ALTER TABLE access_methods DROP CONSTRAINT IF EXISTS access_methods_status_check"
    )
    conn.execute(
        "ALTER TABLE access_methods ADD CONSTRAINT access_methods_status_check "
        "CHECK (status IN ('ok', 'unavailable', 'blocked', 'broken', 'failed', 'never'))"
    )


def _migrate_jobs(conn: DBConn) -> None:
    """Add any jobs columns missing from an older database (the lease/heartbeat columns)."""
    for column, col_type in _JOBS_ADDED_COLUMNS.items():
        # DDL with hardcoded column/type from a module constant (see _migrate_company_stores).
        conn.execute(  # ty: ignore[no-matching-overload]
            f"ALTER TABLE jobs ADD COLUMN IF NOT EXISTS {column} {col_type}"
        )


_UPSERT_ACCESS_METHOD = """
INSERT INTO access_methods
  (target_type, target_key, method, cost_rank, status, resource_url, params,
   record_count, error, attempts, last_ok_at, last_fail_at, updated_at)
VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,1,%s,%s,%s)
ON CONFLICT (target_type, target_key, method) DO UPDATE SET
  cost_rank    = excluded.cost_rank,
  status       = excluded.status,
  -- On success keep/refresh the winning locator; on FAILURE clear it, so the next
  -- attempt re-discovers instead of re-serving a now-broken URL (the stale-hint lock).
  resource_url = CASE WHEN excluded.status = 'ok'
                      THEN COALESCE(excluded.resource_url, access_methods.resource_url)
                      ELSE excluded.resource_url END,
  params       = CASE WHEN excluded.status = 'ok'
                      THEN COALESCE(excluded.params, access_methods.params)
                      ELSE excluded.params END,
  record_count = excluded.record_count,
  error        = excluded.error,
  attempts     = access_methods.attempts + 1,
  last_ok_at   = CASE WHEN excluded.status = 'ok'
                      THEN excluded.updated_at ELSE access_methods.last_ok_at END,
  last_fail_at = CASE WHEN excluded.status = 'failed'
                      THEN excluded.updated_at ELSE access_methods.last_fail_at END,
  updated_at   = excluded.updated_at
"""

# Columns returned by the access_methods getters, in order.
ACCESS_METHOD_COLUMNS = (
    "method", "cost_rank", "status", "resource_url", "params",
    "record_count", "error", "attempts", "last_ok_at", "last_fail_at",
)


def record_access_attempt(
    conn: DBConn,
    target_type: str,
    target_key: str,
    method: str,
    cost_rank: int,
    status: str,
    resource_url: str | None = None,
    params: str | None = None,
    record_count: int | None = None,
    error: str | None = None,
) -> None:
    """Upsert the outcome of one method attempt against one target. Caller commits.

    ``status`` must be one of ``ACCESS_STATUSES``. On 'ok' the last_ok_at timestamp advances; on any
    other outcome, last_fail_at. attempts increments on every call. A null resource_url/params
    preserves the stored value.
    """
    if status not in ACCESS_STATUSES:
        raise ValueError(f"unknown access status {status!r}; expected one of {sorted(ACCESS_STATUSES)}")
    now = datetime.datetime.now(datetime.UTC).isoformat()
    ok_at = now if status == "ok" else None
    # Every outcome that is not a success advances last_fail_at — 'broken' and 'blocked' are failures
    # too, and the staleness governor reads these timestamps. (Before the vocabulary existed this
    # tested `== "failed"`, which would have left the new statuses without a failure time.)
    fail_at = None if status in ("ok", "never") else now
    conn.execute(
        _UPSERT_ACCESS_METHOD,
        (
            target_type, target_key, method, cost_rank, status, resource_url,
            params, record_count, error, ok_at, fail_at, now,
        ),
    )


def get_access_methods(conn: DBConn, target_type: str, target_key: str) -> list[tuple]:
    """Return all recorded method rows for a target (see ACCESS_METHOD_COLUMNS)."""
    return conn.execute(
        "SELECT method, cost_rank, status, resource_url, params, record_count, "
        "error, attempts, last_ok_at, last_fail_at FROM access_methods "
        "WHERE target_type = %s AND target_key = %s ORDER BY cost_rank",
        (target_type, target_key),
    ).fetchall()


def access_health(conn: DBConn, target_type: str | None = None) -> list[tuple[str, str, int]]:
    """Attempt counts per (method, status) — the query a canary runs, and the reason the vocabulary exists.

    A method whose rows are all ``ok`` or ``unavailable`` is healthy: it works, or the world has
    nothing for it. A method accumulating ``broken`` is asking to be repaired, and ``blocked`` says the
    egress is wrong, not the code. Before the vocabulary, all three read ``failed`` and no query could
    tell them apart — so a rung that died because an endpoint moved stayed green for weeks.

    Ordered worst-first: broken, then blocked, then the rest.
    """
    sql = (
        "SELECT method, status, count(*) FROM access_methods "
        + ("WHERE target_type = %s " if target_type else "")
        + "GROUP BY method, status "
        "ORDER BY CASE status WHEN 'broken' THEN 0 WHEN 'blocked' THEN 1 WHEN 'failed' THEN 2 "
        "ELSE 3 END, count(*) DESC, method"
    )
    params = (target_type,) if target_type else ()
    return [(row[0], row[1], row[2]) for row in conn.execute(sql, params).fetchall()]


def get_access_winner(
    conn: DBConn, target_type: str, target_key: str
) -> tuple | None:
    """Return the cheapest 'ok' method row for a target, or None (see columns)."""
    return conn.execute(
        "SELECT method, cost_rank, status, resource_url, params, record_count, "
        "error, attempts, last_ok_at, last_fail_at FROM access_methods "
        "WHERE target_type = %s AND target_key = %s AND status = 'ok' "
        "ORDER BY cost_rank LIMIT 1",
        (target_type, target_key),
    ).fetchone()




_UPSERT_ATTESTATION = """
INSERT INTO attestations (subject_type, subject, predicate, object, source_type, source_ref,
                          source_url, quote, confidence, retrieved_at, notes)
VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
ON CONFLICT (subject_type, subject, predicate, object, source_ref) DO UPDATE SET
    source_type = EXCLUDED.source_type,
    source_url  = EXCLUDED.source_url,
    quote       = EXCLUDED.quote,
    confidence  = EXCLUDED.confidence,
    retrieved_at = EXCLUDED.retrieved_at,
    notes       = EXCLUDED.notes,
    updated_at  = now()
"""


def upsert_attestation(conn: DBConn, record: Attestation) -> None:
    """Record one externally-sourced fact and the evidence for it. Caller must commit.

    Keyed on the triple *plus* ``source_ref``: two sources may attest the same fact, and a reader is
    better served by both than by whichever was written last.
    """
    conn.execute(
        _UPSERT_ATTESTATION,
        (
            record.subject_type,
            record.subject,
            record.predicate,
            record.object,
            record.source_type,
            record.source_ref,
            record.source_url,
            record.quote,
            record.confidence,
            record.retrieved_at,
            record.notes,
        ),
    )


def attestations_for(
    conn: DBConn, subject_type: str, subject: str, predicate: str | None = None
) -> list[Attestation]:
    """Every recorded fact about a subject, most recently retrieved first. Case-insensitive subject.

    Returns the *evidence*, not a verdict: a caller that finds two rows disagreeing has learned
    something true about the world, and should not silently take one.
    """
    sql = (
        "SELECT subject_type, subject, predicate, object, source_type, source_ref, retrieved_at, "
        "source_url, quote, confidence, notes FROM attestations "
        "WHERE subject_type = %s AND lower(subject) = lower(%s)"
    )
    params: list[object] = [subject_type, subject]
    if predicate is not None:
        sql += " AND predicate = %s"
        params.append(predicate)
    sql += " ORDER BY retrieved_at DESC, source_ref"
    rows = conn.execute(sql, tuple(params)).fetchall()
    return [
        Attestation(
            subject_type=r[0], subject=r[1], predicate=r[2], object=r[3], source_type=r[4],
            source_ref=r[5], retrieved_at=str(r[6]), source_url=r[7], quote=r[8],
            confidence=r[9], notes=r[10],
        )
        for r in rows
    ]


def __getattr__(name: str) -> Any:
    """Back-compat delegation: the cannabis reference schema + CRUD moved to ``rung.reference_db``
    (genericization B1/B3). ``from rung import db; db.insert_dispensary(...)`` still resolves — routed
    here lazily so importing the *engine* ``db`` (as ``queue``/``access`` do) loads no cannabis
    ``models``/``text``. Returns ``Any`` (PEP 562 idiom); re-point call sites to ``rung.reference_db``
    for full typing (B5). Prefer importing ``rung.reference_db`` directly in new code."""
    import rung.reference_db as _ref
    try:
        return getattr(_ref, name)
    except AttributeError:
        raise AttributeError(f"module 'rung.db' has no attribute {name!r}") from None
