"""The cannabis reference-application schema + CRUD — the reference half split out of the engine ``db``.

Split from ``db.py`` (genericization Workstream B1/B3, ``docs/genericization_plan.md``) so the generic
engine (``db``, imported by ``queue``/``access``) no longer drags in the cannabis record types + terpene
taxonomy. Holds the cannabis tables (dispensaries / company_stores / store_products / products /
product_observations / store_locations / store_observations / store_lifecycle_events /
state_programs + the ``products_normalized`` view), their
migrations, all the CRUD, and ``create_reference_tables`` / ``create_tables``.
Imports the engine primitives from ``db``. Back-compat: ``db.<reference fn>`` still works via
``db.__getattr__`` delegating here.

IT ALSO OWNS THE **ANALYSIS GUARDS** — and those exist because analyses were RETRACTED:

* ``NATURAL_FLOWER_WHERE`` / ``natural_flower_where(alias)`` — natural flower only. Infused flower
  inflated a producer→THC effect 0.226 → 0.372. **Take the aliased form** when your query needs a
  prefix: three live scripts hand-rolled the filter because the bare constant would not compose, and
  all three kept an older, shorter regex that admitted concentrates AS FLOWER.
* ``TRUSTED_LINEAGE_WHERE`` — excludes Weedmaps, whose ``strain_type`` is a defaulted field (98.2%
  "Indica"); a lineage finding built on it was retracted.
* ``TRUSTED_POTENCY_WHERE`` / ``trusted_potency_where(alias)`` — excludes Leafly, which is 8.4% of
  natural-flower rows but supplies **60% of the impossible (≥40% THC) tail**, differentially by state.
* ``US_JURISDICTIONS_SUBQUERY`` / ``US_EXCL_TERRITORIES_SUBQUERY`` / ``CA_PROVINCES_SUBQUERY`` and
  ``us_jurisdictions_where(col)`` — country partitioning, so a CAD price never pools with a USD one.

All are ``LiteralString`` so they compose into SQL without defeating psycopg's injection guard. **Reach
them from HERE, not through ``db.*``** — the ``db.__getattr__`` shim erases ``LiteralString`` to ``Any``
for any name missing from its ``TYPE_CHECKING`` block.
"""

import contextlib
import datetime
import json
from typing import LiteralString

from psycopg.types.json import Jsonb

from rung import text
from rung.db import DBConn, create_engine_tables
from rung.models import (
    CompanyReconRecord,
    CompanyStoreRecord,
    DispensaryRecord,
    LifecycleEventRecord,
    LocationObservation,
    StateProgramRecord,
    StoreProductRecord,
)

_CREATE_DISPENSARIES = """
CREATE TABLE IF NOT EXISTS dispensaries (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source            TEXT    NOT NULL,
    name              TEXT,
    address           TEXT,
    city              TEXT,
    state             TEXT,
    zip_code          TEXT,
    phone             TEXT,
    website           TEXT,
    latitude          DOUBLE PRECISION,
    longitude         DOUBLE PRECISION,
    scraped_at        TEXT    NOT NULL
)
"""

# company_id logically references companies(id), but the companies table is owned
# (and created later) by seed_companies.py, so no FK constraint — Postgres would
# reject DDL referencing a not-yet-existing table. SQLite never enforced it either.
# Geocoded locations survive a roster re-scrape ONLY because they are cached here.
#
# `scrape-states` replaces a state's rows with DELETE + INSERT (`delete_dispensaries_for_state`), and
# the source republishes only what the source publishes. For the rosters that carry a street but no
# ZIP — NV, IL, UT, MD and others — the latitude/longitude/zip_code/city that `backfill_geocode.py`
# derived are therefore DESTROYED by the next successful scrape. `compare.geo_key` is `@lat,lon|zip`
# and `_match_key` is `number street|zip`, so a roster with no ZIP matches NOTHING: the deliverable
# silently stops working for that state, with no error, on a scrape that succeeded.
#
# That is not hypothetical. It happened on 2026-07-12, reverting the NV and MD fixes that
# `WORK_BACKLOG.md` still records as DONE, and nobody saw it because the one instrument that checks
# (`coverage_healthcheck.py`) was muted in the sweep.
#
# The existing guard in `scrape_all_states` protects against the failure that was ANTICIPATED (an
# empty scrape wiping good rows) and is blind to the one that occurred (a successful scrape wiping
# DERIVED rows). So: cache every geocode keyed by the one-line query (`text.geocode_query`), and have
# the command that destroys the enrichment restore it, in the same commit. Re-applying costs zero
# geocoder calls, which is what makes "restore on every scrape" affordable.
_CREATE_GEOCODE_CACHE = """
CREATE TABLE IF NOT EXISTS geocode_cache (
    query        TEXT PRIMARY KEY,
    latitude     DOUBLE PRECISION,
    longitude    DOUBLE PRECISION,
    zip_code     TEXT,
    city         TEXT,
    geocoded_at  TIMESTAMPTZ NOT NULL DEFAULT now()
)
"""

_CREATE_COMPANY_RECON = """
CREATE TABLE IF NOT EXISTS company_recon (
    company_id     INTEGER NOT NULL,
    canonical_name TEXT    NOT NULL,
    homepage_url   TEXT,
    platform       TEXT,
    confidence     TEXT,
    http_status    INTEGER,
    error          TEXT,
    scouted_at     TEXT    NOT NULL,
    PRIMARY KEY (company_id)
)
"""

_CREATE_COMPANY_STORES = """
CREATE TABLE IF NOT EXISTS company_stores (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id     INTEGER NOT NULL,
    canonical_name TEXT    NOT NULL,
    state          TEXT    NOT NULL,
    source         TEXT    NOT NULL,
    name           TEXT,
    address        TEXT,
    city           TEXT,
    zip_code       TEXT,
    phone          TEXT,
    website        TEXT,
    latitude       DOUBLE PRECISION,
    longitude      DOUBLE PRECISION,
    platform       TEXT,
    external_id    TEXT,
    store_url      TEXT,
    canonical_company_id INTEGER,
    storefront_name TEXT,
    scraped_at     TEXT    NOT NULL
)
"""

# Scrape-handle columns added after company_stores first shipped; create_tables
# adds any missing so existing databases upgrade in place. canonical_company_id is
# set by the dedupe step: NULL = this row is canonical/unique; non-NULL points to the
# operator's canonical company (the row is a shared-brand duplicate, e.g. Delta 9 /
# Keystone IC stores that are really Sunnyside).
_COMPANY_STORE_ADDED_COLUMNS = {
    "platform": "TEXT",
    "external_id": "TEXT",
    "store_url": "TEXT",
    "canonical_company_id": "INTEGER",
    # The brand on THIS location's storefront (the alias name where one applies),
    # for reporting. Distinct from the operator (the dedup/grouping key).
    "storefront_name": "TEXT",
}

_INSERT_DISPENSARY = """
INSERT INTO dispensaries
  (source, name, address, city, state, zip_code, phone,
   website, latitude, longitude, scraped_at)
VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
"""

_UPSERT_RECON = """
INSERT INTO company_recon
  (company_id, canonical_name, homepage_url, platform, confidence,
   http_status, error, scouted_at)
VALUES (%s,%s,%s,%s,%s,%s,%s,%s)
ON CONFLICT (company_id) DO UPDATE SET
  canonical_name = excluded.canonical_name,
  homepage_url   = excluded.homepage_url,
  platform       = excluded.platform,
  confidence     = excluded.confidence,
  http_status    = excluded.http_status,
  error          = excluded.error,
  scouted_at     = excluded.scouted_at
"""

# Stage-3 menu snapshots. Keyed by store_key (= "{platform}:{external_id}") rather
# than company_stores.id because the keep-the-best replace regenerates store ids;
# company_id/state ride along for joins and per-state reporting.
_CREATE_STORE_PRODUCTS = """
CREATE TABLE IF NOT EXISTS store_products (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          INTEGER NOT NULL,
    state               TEXT    NOT NULL,
    store_key           TEXT    NOT NULL,
    platform            TEXT    NOT NULL,
    external_id         TEXT    NOT NULL,
    source              TEXT    NOT NULL,
    external_product_id TEXT,
    name                TEXT,
    brand               TEXT,
    category            TEXT,
    category_std        TEXT,
    -- TRUE when category_std was CORRECTED from the product NAME (category_name_overrides.yml) rather
    -- than read from the platform's raw category — OUR correction (a capsule sold as an "edible"), not
    -- the platform's own label. Same shape as product_type_defaulted below. See `text.category_overridden`.
    category_overridden BOOLEAN,
    product_type_std    TEXT,
    -- TRUE when product_type_std was MANUFACTURED from absence (no keyword matched, so the category's
    -- `_defaults` label fired) rather than read from the product name. This is the `strain_type` bug's
    -- shape on OUR side of the wire: Weedmaps shipped a defaulted lineage field, we read it as an
    -- observation, and we retracted a finding (E1) over it. 82.5% of flower rows carry a `Bud` that no
    -- name ever said. The default is a defensible prior; it is not an observation, and an analysis must
    -- be able to tell them apart. See `text.product_type_defaulted`.
    product_type_defaulted BOOLEAN,
    -- The obtention method the NAME or the platform's RAW category declares: 'Infused' (added to the
    -- bud) / 'Extracted' (taken out of the plant) / NULL = neither says. There is deliberately NO
    -- 'Natural' value: 96.35% of Flower rows declare nothing, and stamping those would manufacture
    -- 903,819 observations nobody made — the `product_type_defaulted` comment above is the same
    -- lesson, learned the hard way. So NULL means "unstated", and NATURAL_FLOWER_WHERE asks for
    -- exactly that. See `text.normalize_obtention` + reports/obtention_facet_design.md.
    obtention_std       TEXT,
    strain_type         TEXT,
    strain_type_std     TEXT,
    price               DOUBLE PRECISION,
    size_g              DOUBLE PRECISION,
    thc                 DOUBLE PRECISION,
    cbd                 DOUBLE PRECISION,
    thc_mg              DOUBLE PRECISION,
    cbd_mg              DOUBLE PRECISION,
    terpenes            JSONB,
    terpenes_std        JSONB,
    terp_total          DOUBLE PRECISION,
    -- TRUE when normalize_terpenes ALTERED the raw values to produce terpenes_std/terp_total (a lone
    -- spike dropped, an unlabeled mg/g row rescaled ÷10, or a single terpene above the per-terpene
    -- ceiling dropped) — OUR correction, not the published profile, and these feed D1's ICC/variance
    -- flagship, so an analysis must be able to exclude them. See `normalize.terpenes_repaired`.
    terpenes_repaired   BOOLEAN,
    cannabinoids_std    JSONB,
    variants            JSONB,
    scraped_at          TEXT    NOT NULL,
    -- The percent-OR-mg potency contract (CLAUDE.md): a cannabinoid is published as a percent
    -- (thc/cbd) OR a per-dose mg (thc_mg/cbd_mg), never both. The extractors route by the
    -- platform's unit; this makes the invariant a schema guarantee, not just a convention.
    CONSTRAINT store_products_potency_unit_check
        CHECK ((thc IS NULL OR thc_mg IS NULL) AND (cbd IS NULL OR cbd_mg IS NULL))
)
"""

# store_products columns added after the table's first release — applied in-place by
# _migrate_store_products so an existing database picks them up.
_STORE_PRODUCT_ADDED_COLUMNS = {
    "thc_mg": "DOUBLE PRECISION",
    "cbd_mg": "DOUBLE PRECISION",
    "category_std": "TEXT",
    "category_overridden": "BOOLEAN",
    "product_type_std": "TEXT",
    "obtention_std": "TEXT",
    "product_type_defaulted": "BOOLEAN",
    "strain_type_std": "TEXT",
    "size_g": "DOUBLE PRECISION",
    "terpenes_std": "JSONB",
    "terp_total": "DOUBLE PRECISION",
    "terpenes_repaired": "BOOLEAN",
    "cannabinoids_std": "JSONB",
}

# The percent-OR-mg potency CHECK, added in-place to a database created before the constraint
# existed. Postgres has no ADD CONSTRAINT IF NOT EXISTS, so the DO block swallows duplicate_object
# to stay idempotent (a fresh table already carries the constraint from _CREATE_STORE_PRODUCTS).
# Pre-flight scan 2026-07-02: 0 of 4.8M live rows violate it, so it validates without cleanup.
_MIGRATE_STORE_PRODUCTS_POTENCY_CHECK = """
DO $$ BEGIN
    ALTER TABLE store_products ADD CONSTRAINT store_products_potency_unit_check
        CHECK ((thc IS NULL OR thc_mg IS NULL) AND (cbd IS NULL OR cbd_mg IS NULL));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
"""

_CREATE_STORE_PRODUCTS_STORE_INDEX = """
CREATE INDEX IF NOT EXISTS store_products_store_key ON store_products (store_key)
"""

# Per-state read paths. `store_products` (4.8M rows) is grouped by store_key per state once at
# every `scrape-menus` startup (`latest_snapshot_times`) — a `(state, store_key)` index turns that
# from a full scan into an index-only scan (the `(store_key)` index above stays for the per-store
# `WHERE store_key = %s` lookups). `company_stores` is filtered by `(company_id, state)` five times
# per company in the Stage-2 keep-the-best replace and by `state` alone in dedupe/compare; a
# `(state, company_id)` composite serves both (two equality predicates + the leftmost-prefix
# state-only scans).
_CREATE_STORE_PRODUCTS_STATE_INDEX = """
CREATE INDEX IF NOT EXISTS store_products_state_store_key ON store_products (state, store_key)
"""
_CREATE_COMPANY_STORES_STATE_INDEX = """
CREATE INDEX IF NOT EXISTS company_stores_state_company ON company_stores (state, company_id)
"""

# Master product DB. `store_products` stays the live
# snapshot (overwritten each scrape); these two tables accumulate HISTORY the snapshot throws away.
# `products` = one row per distinct product ever seen (identity = the text.product_fingerprint tuple,
# potency/terpenes excluded since they vary by batch). `product_observations` = an APPEND-ONLY log of
# price/potency/terpenes stamped with scraped_at — never updated, never deleted — the substrate for
# longitudinal analyses. Scoped to consumable categories (_OBSERVED_CATEGORIES); a plain indexed
# table (partition later if it grows).
_CREATE_PRODUCTS = """
CREATE TABLE IF NOT EXISTS products (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fingerprint      TEXT NOT NULL UNIQUE,
    brand            TEXT,
    name             TEXT,
    category_std     TEXT,
    product_type_std TEXT,
    obtention_std    TEXT,
    strain_type_std  TEXT,
    size_g           DOUBLE PRECISION,
    first_seen       TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen        TIMESTAMPTZ NOT NULL DEFAULT now()
)
"""

#: Columns added to `products` after its first release — the seam `products` DID NOT HAVE, and whose
#: absence is the whole bug. `natural_flower_where(alias)` is aliasable **precisely so it can be used on
#: this table** (`p.category_std = 'Flower' AND p.obtention_std IS NULL`), so the guard's design assumes
#: the facet exists here. When #293 introduced `obtention_std` it landed in `_STORE_PRODUCT_ADDED_COLUMNS`
#: and had nowhere to land for `products` — every sibling table has a `_migrate_*`, this one did not — so
#: the master silently stayed behind and `thc_inflation_by_jurisdiction.py`'s history half died with
#: `UndefinedColumn`. `test_reference_db.py` now asserts every aliasable-guard column exists on every
#: table the guard is aliased onto, which is the check that would have caught it.
_PRODUCT_ADDED_COLUMNS = {
    "obtention_std": "TEXT",
}
_CREATE_PRODUCT_OBSERVATIONS = """
CREATE TABLE IF NOT EXISTS product_observations (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id    BIGINT  NOT NULL,
    store_key     TEXT    NOT NULL,
    state         TEXT    NOT NULL,
    price         DOUBLE PRECISION,
    thc           DOUBLE PRECISION,
    cbd           DOUBLE PRECISION,
    thc_mg        DOUBLE PRECISION,
    cbd_mg        DOUBLE PRECISION,
    terpenes_std  JSONB,
    terp_total    DOUBLE PRECISION,
    cannabinoids_std JSONB,
    scraped_at    TIMESTAMPTZ NOT NULL
)
"""
# product_observations columns added after first release — applied by _migrate_product_observations.
_PRODUCT_OBSERVATIONS_ADDED_COLUMNS = {
    "cannabinoids_std": "JSONB",
}
_CREATE_PRODUCT_OBSERVATIONS_PRODUCT_INDEX = """
CREATE INDEX IF NOT EXISTS product_observations_product ON product_observations (product_id, scraped_at)
"""
_CREATE_PRODUCT_OBSERVATIONS_STORE_INDEX = """
CREATE INDEX IF NOT EXISTS product_observations_store ON product_observations (store_key, scraped_at)
"""

# Store-lifecycle history. `company_stores` stays the live snapshot (overwritten each scrape);
# these two accumulate the history the snapshot throws away — the substrate for open/close/acquired
# detection (see docs/store_history_design.md). `store_locations` = one row per distinct PHYSICAL
# location ever seen (identity = the dedupe geo_key/address_key, computed in the overlay since the
# key builders live in sources/dedupe.py); `store_observations` = an APPEND-ONLY log of the operator
# / storefront / menu-handle seen at that location, stamped with observed_at — never updated or
# deleted. Change-detected + a daily presence heartbeat, exactly like product_observations.
_CREATE_STORE_LOCATIONS = """
CREATE TABLE IF NOT EXISTS store_locations (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_key  TEXT NOT NULL UNIQUE,
    state         TEXT,
    latitude      DOUBLE PRECISION,
    longitude     DOUBLE PRECISION,
    address       TEXT,
    city          TEXT,
    zip_code      TEXT,
    first_seen    TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen     TIMESTAMPTZ NOT NULL DEFAULT now()
)
"""
_CREATE_STORE_OBSERVATIONS = """
CREATE TABLE IF NOT EXISTS store_observations (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id   BIGINT NOT NULL,
    source        TEXT   NOT NULL,
    operator      TEXT,
    storefront_name TEXT,
    platform      TEXT,
    external_id   TEXT,
    address       TEXT,
    city          TEXT,
    observed_at   TIMESTAMPTZ NOT NULL
)
"""
_CREATE_STORE_OBSERVATIONS_LOCATION_INDEX = """
CREATE INDEX IF NOT EXISTS store_observations_location ON store_observations (location_id, observed_at)
"""

# Phase 2: the DERIVED lifecycle. `store_observations` is the append-only evidence; this table is the
# conclusion drawn from all of it (`store-lifecycle --write`), materialized so maps and the patient UI
# can read events directly instead of re-deriving. Recomputed wholesale per state — never appended —
# because a later observation can revise an earlier verdict (a "closed" store that reappears was
# never closed). Display fields live on store_locations; join, don't duplicate.
_CREATE_STORE_LIFECYCLE_EVENTS = """
CREATE TABLE IF NOT EXISTS store_lifecycle_events (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id         BIGINT NOT NULL,
    state               TEXT   NOT NULL,
    source              TEXT   NOT NULL,
    kind                TEXT   NOT NULL,
    occurred_on         DATE   NOT NULL,
    operator            TEXT,
    previous_operator   TEXT,
    confidence          TEXT,
    related_location_id BIGINT,
    derived_at          TIMESTAMPTZ NOT NULL DEFAULT now()
)
"""
_CREATE_STORE_LIFECYCLE_EVENTS_STATE_INDEX = """
CREATE INDEX IF NOT EXISTS store_lifecycle_events_state
ON store_lifecycle_events (state, occurred_on)
"""
_CREATE_STORE_LIFECYCLE_EVENTS_LOCATION_INDEX = """
CREATE INDEX IF NOT EXISTS store_lifecycle_events_location
ON store_lifecycle_events (location_id)
"""

# The combined cross-platform surface: one row per product carrying only the standardized
# fields (canonical category, grams, percent/mg potency, the price-per-gram derived from the
# representative size, and the folded terpenes). The raw platform-shaped columns
# (category/terpenes/variants) stay on store_products; this view is what callers query for
# apples-to-apples comparison across platforms and states.
#
# `currency` is derived (not stored per-row): the store's country determines it — every
# CA-province store is CAD, every US store USD — via state_programs.country, a total mapping,
# so a per-row column would only duplicate it (design decision D2, docs/canada_expansion.md).
# `price`/`price_per_g` stay numeric in their native currency; any cross-country price analysis
# MUST partition or convert by this column, never pool CAD with USD.
# Currency is a total function of the store's country (state_programs.country): every CA-province
# store is CAD, every other store USD (design decision D2, docs/canada_expansion.md). Defined once
# here so the normalized surface and the FX-converted observations view derive it identically. Both
# views MUST alias state_programs as `prog` for this to resolve.
_CURRENCY_FROM_COUNTRY: LiteralString = "CASE WHEN prog.country = 'CA' THEN 'CAD' ELSE 'USD' END"

# Daily foreign-exchange series for cross-currency price normalization (docs/fx_series_design.md).
# `rate` is quote_ccy per 1 base_ccy (a base-priced value * rate = that value in quote_ccy). We store
# the direction analyses need — base=CAD, quote=USD — so a CAD price converts by a plain multiply.
# FX sources publish business days only; a row exists for EVERY calendar day, and the forward-filled
# ones (weekend/holiday) carry is_carried=TRUE, so the join is a plain equality while "what the
# source actually published" stays auditable. A missing rate is an ABSENT row, never a fabricated
# 1.0 — a self-inflicted fetch gap must not become a fact about the day.
_CREATE_FX_RATES = """
CREATE TABLE IF NOT EXISTS fx_rates (
    rate_date   DATE NOT NULL,
    base_ccy    TEXT NOT NULL,
    quote_ccy   TEXT NOT NULL,
    rate        DOUBLE PRECISION NOT NULL,
    source      TEXT NOT NULL,
    is_carried  BOOLEAN NOT NULL DEFAULT FALSE,
    fetched_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (rate_date, base_ccy, quote_ccy)
)
"""

_CREATE_PRODUCTS_NORMALIZED_VIEW = f"""
CREATE OR REPLACE VIEW products_normalized AS
SELECT
    sp.id, sp.company_id, sp.state, sp.store_key, sp.platform, sp.source, sp.external_product_id,
    sp.name, sp.brand, sp.category_std AS category, sp.strain_type_std AS strain_type,
    sp.price, sp.size_g,
    CASE WHEN sp.size_g > 0 AND sp.price IS NOT NULL
         THEN round((sp.price / sp.size_g)::numeric, 2) END AS price_per_g,
    sp.thc, sp.cbd, sp.thc_mg, sp.cbd_mg, sp.terp_total, sp.terpenes_std,
    sp.scraped_at,
    sp.product_type_std AS product_type,
    sp.cannabinoids_std,  -- appended: CREATE OR REPLACE VIEW only allows adding columns at the end
    {_CURRENCY_FROM_COUNTRY} AS currency,
    sp.obtention_std      -- appended (same constraint); NOT renamed, so the natural-flower predicate
                          -- reads identically here and against store_products
FROM store_products sp
LEFT JOIN state_programs prog ON prog.abbr = sp.state
"""

# The durable price series (product_observations) converted to a common numeraire (USD) at the rate
# that prevailed ON EACH OBSERVATION'S DATE — the reason to hold a series and not one flat rate. USD
# rows need no conversion (fx_rate 1.0); a CAD row with no same-day rate gets a NULL price_usd
# (LEFT JOIN) rather than a wrong one. price_usd is a SPOT-FX conversion, not purchasing-power
# parity — read docs/fx_series_design.md §0 before pooling it across markets.
_CREATE_PRODUCT_OBSERVATIONS_FX_VIEW = f"""
CREATE OR REPLACE VIEW product_observations_fx AS
SELECT
    po.id, po.product_id, po.store_key, po.state, po.scraped_at,
    po.price, po.thc, po.cbd, po.thc_mg, po.cbd_mg, po.terp_total, po.terpenes_std,
    {_CURRENCY_FROM_COUNTRY} AS currency,
    CASE WHEN {_CURRENCY_FROM_COUNTRY} = 'USD' THEN 1.0 ELSE fx.rate END AS fx_rate,
    CASE
        WHEN po.price IS NULL THEN NULL
        WHEN {_CURRENCY_FROM_COUNTRY} = 'USD' THEN po.price
        WHEN fx.rate IS NULL THEN NULL
        ELSE round((po.price * fx.rate)::numeric, 2)
    END AS price_usd
FROM product_observations po
LEFT JOIN state_programs prog ON prog.abbr = po.state
LEFT JOIN fx_rates fx
       ON fx.base_ccy = {_CURRENCY_FROM_COUNTRY}
      AND fx.quote_ccy = 'USD'
      AND fx.rate_date = (po.scraped_at AT TIME ZONE 'UTC')::date
"""

# NOTE the column list is EXHAUSTIVE and hand-maintained: a stamped field that is missing here is
# computed at `menu_extractors._record` and then silently dropped on the floor. That is not
# hypothetical — `product_type_defaulted` was absent from this list from the day it was added, so
# every row scraped after the one-off backfill carried NULL: 3.19M rows (100% of 2026-07-15/16) with
# no value for the very flag that exists to keep a DEFAULT from being read as an OBSERVATION. The
# backfill made the column look populated, which is what hid it. Add the column here when you add the
# field, or the field does not exist.
_INSERT_STORE_PRODUCT = """
INSERT INTO store_products
  (company_id, state, store_key, platform, external_id, source,
   external_product_id, name, brand, category, category_std, category_overridden, product_type_std,
   product_type_defaulted, obtention_std,
   strain_type, strain_type_std,
   price, size_g, thc, cbd, thc_mg, cbd_mg, terpenes, terpenes_std, terp_total, terpenes_repaired,
   cannabinoids_std, variants, scraped_at)
VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
"""

_INSERT_COMPANY_STORE = """
INSERT INTO company_stores
  (company_id, canonical_name, state, source, name, address, city,
   zip_code, phone, website, latitude, longitude, platform, external_id,
   store_url, scraped_at)
VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
"""


def create_reference_tables(conn: DBConn) -> None:
    """Create the **cannabis reference-application** tables — ``dispensaries``, ``company_recon``,
    ``company_stores``, ``state_programs``, ``store_products``, ``products``/``product_observations``,
    ``store_locations``/``store_observations``/``store_lifecycle_events`` — plus their indexes,
    in-place migrations, and the
    ``products_normalized`` view. This is the schema of *the reference pipeline*, not the engine; a
    general plugin does not call it. Idempotent; commits.

    Does not create the companies table — that is owned by seed_companies.py.
    """
    conn.execute(_CREATE_DISPENSARIES)
    conn.execute(_CREATE_GEOCODE_CACHE)
    conn.execute(_CREATE_COMPANY_RECON)
    conn.execute(_CREATE_COMPANY_STORES)
    conn.execute(_CREATE_STATE_PROGRAMS)
    conn.execute(_CREATE_STORE_PRODUCTS)
    conn.execute(_CREATE_STORE_PRODUCTS_STORE_INDEX)
    conn.execute(_CREATE_STORE_PRODUCTS_STATE_INDEX)
    conn.execute(_CREATE_COMPANY_STORES_STATE_INDEX)
    conn.execute(_CREATE_PRODUCTS)
    conn.execute(_CREATE_PRODUCT_OBSERVATIONS)
    conn.execute(_CREATE_PRODUCT_OBSERVATIONS_PRODUCT_INDEX)
    conn.execute(_CREATE_PRODUCT_OBSERVATIONS_STORE_INDEX)
    conn.execute(_CREATE_FX_RATES)
    conn.execute(_CREATE_STORE_LOCATIONS)
    conn.execute(_CREATE_STORE_OBSERVATIONS)
    conn.execute(_CREATE_STORE_OBSERVATIONS_LOCATION_INDEX)
    conn.execute(_CREATE_STORE_LIFECYCLE_EVENTS)
    conn.execute(_CREATE_STORE_LIFECYCLE_EVENTS_STATE_INDEX)
    conn.execute(_CREATE_STORE_LIFECYCLE_EVENTS_LOCATION_INDEX)
    _migrate_company_stores(conn)
    _migrate_state_programs(conn)
    _migrate_store_products(conn)
    _migrate_products(conn)
    _migrate_product_observations(conn)
    _migrate_dispensaries(conn)
    conn.execute(_CREATE_PRODUCTS_NORMALIZED_VIEW)  # after the migration adds its columns
    conn.execute(_CREATE_PRODUCT_OBSERVATIONS_FX_VIEW)  # depends on fx_rates + product_observations
    conn.commit()


def create_tables(conn: DBConn) -> None:
    """Create every table — the engine infra **and** the cannabis reference schema. Thin wrapper over
    ``create_engine_tables`` + ``create_reference_tables``; the reference application's whole-schema call.

    Does not create the companies table — that is owned by seed_companies.py.
    """
    create_engine_tables(conn)
    create_reference_tables(conn)


# --- FX series (docs/fx_series_design.md) -----------------------------------------------------------

def ensure_fx_rates(conn: DBConn) -> None:
    """Idempotently create the ``fx_rates`` table and the ``product_observations_fx`` view.

    For the ``fetch-fx`` command, which may run on a database created before this schema landed;
    ``create_reference_tables`` also creates them. Commits.
    """
    conn.execute(_CREATE_FX_RATES)
    conn.execute(_CREATE_PRODUCT_OBSERVATIONS_FX_VIEW)
    conn.commit()


def upsert_fx_rates(
    conn: DBConn, rows: list[tuple[datetime.date, str, str, float, str, bool]]
) -> None:
    """Insert/refresh FX rows ``(rate_date, base_ccy, quote_ccy, rate, source, is_carried)``.

    ``fetched_at`` is stamped ``now()``. Idempotent on the ``(rate_date, base_ccy, quote_ccy)`` key —
    a re-fetch is a better reading of the day, not a second fact about it. Caller commits.
    """
    if not rows:
        return
    with conn.cursor() as cur:
        cur.executemany(
            "INSERT INTO fx_rates "
            "  (rate_date, base_ccy, quote_ccy, rate, source, is_carried, fetched_at) "
            "VALUES (%s, %s, %s, %s, %s, %s, now()) "
            "ON CONFLICT (rate_date, base_ccy, quote_ccy) DO UPDATE SET "
            "  rate = EXCLUDED.rate, source = EXCLUDED.source, "
            "  is_carried = EXCLUDED.is_carried, fetched_at = now()",
            rows,
        )


def fx_backfill_start(conn: DBConn) -> datetime.date | None:
    """Earliest priced observation date across the durable series and the snapshot — the day the FX
    backfill must reach. ``None`` if no priced rows exist yet.

    ``store_products.scraped_at`` is ISO-8601 TEXT, so its date is the leading 10 chars;
    ``product_observations.scraped_at`` is ``timestamptz``. ``LEAST`` ignores NULLs, so an empty
    table on either side does not swallow the other.
    """
    row = conn.execute(
        "SELECT LEAST("
        "  (SELECT min((scraped_at AT TIME ZONE 'UTC')::date) "
        "     FROM product_observations WHERE price IS NOT NULL),"
        "  (SELECT min(substr(scraped_at, 1, 10)::date) "
        "     FROM store_products WHERE price IS NOT NULL)"
        ")"
    ).fetchone()
    return row[0] if row else None


def currencies_needing_conversion(conn: DBConn) -> set[str]:
    """Non-USD currencies present in the priced snapshot — the base currencies whose FX pairs we must
    fetch. Empty when the data is US-only.
    """
    rows = conn.execute(
        f"SELECT DISTINCT {_CURRENCY_FROM_COUNTRY} "
        "FROM store_products sp LEFT JOIN state_programs prog ON prog.abbr = sp.state "
        "WHERE sp.price IS NOT NULL"
    ).fetchall()
    return {row[0] for row in rows if row[0] and row[0] != "USD"}


def fx_rate_coverage(conn: DBConn, base: str, quote: str) -> tuple:
    """``(min_date, max_date, n_days, n_carried)`` for one pair — the ``fetch-fx`` summary line."""
    row = conn.execute(
        "SELECT min(rate_date), max(rate_date), count(*), "
        "       count(*) FILTER (WHERE is_carried) "
        "FROM fx_rates WHERE base_ccy = %s AND quote_ccy = %s",
        (base, quote),
    ).fetchone()
    return row if row else (None, None, 0, 0)


def latest_fx_rate(conn: DBConn, base: str, quote: str) -> float | None:
    """Most recent stored rate for a pair, or ``None`` if the pair has never been fetched."""
    row = conn.execute(
        "SELECT rate FROM fx_rates WHERE base_ccy = %s AND quote_ccy = %s "
        "ORDER BY rate_date DESC LIMIT 1",
        (base, quote),
    ).fetchone()
    return row[0] if row else None


# dispensaries columns removed after first release — always-NULL dead columns never set by any
# extractor or read back (audit L-19); dropped in-place from an older database.
_DISPENSARY_DROPPED_COLUMNS = ("product_available", "open_date", "open_on")


def _migrate_dispensaries(conn: DBConn) -> None:
    """Drop the dead always-NULL columns from an older database (audit L-19)."""
    for column in _DISPENSARY_DROPPED_COLUMNS:
        # DDL with a hardcoded column name from an all-literal module constant (LiteralString).
        conn.execute(f"ALTER TABLE dispensaries DROP COLUMN IF EXISTS {column}")


def _migrate_product_observations(conn: DBConn) -> None:
    """Add any product_observations columns missing from an older database."""
    for column, col_type in _PRODUCT_OBSERVATIONS_ADDED_COLUMNS.items():
        # DDL with hardcoded column/type from a module constant (see _migrate_company_stores).
        conn.execute(  # ty: ignore[no-matching-overload]
            f"ALTER TABLE product_observations ADD COLUMN IF NOT EXISTS {column} {col_type}"
        )


def _migrate_products(conn: DBConn) -> None:
    """Add any products columns missing from an older database.

    The seam that did not exist until 2026-07-17. See `_PRODUCT_ADDED_COLUMNS`.
    """
    for column, col_type in _PRODUCT_ADDED_COLUMNS.items():
        # DDL with hardcoded column/type from a module constant (see _migrate_company_stores).
        conn.execute(  # ty: ignore[no-matching-overload]
            f"ALTER TABLE products ADD COLUMN IF NOT EXISTS {column} {col_type}"
        )


def _migrate_store_products(conn: DBConn) -> None:
    """Add any store_products columns missing from an older database, then the potency CHECK."""
    for column, col_type in _STORE_PRODUCT_ADDED_COLUMNS.items():
        # DDL with hardcoded column/type from a module constant (see _migrate_company_stores).
        conn.execute(  # ty: ignore[no-matching-overload]
            f"ALTER TABLE store_products ADD COLUMN IF NOT EXISTS {column} {col_type}"
        )
    conn.execute(_MIGRATE_STORE_PRODUCTS_POTENCY_CHECK)


def _migrate_company_stores(conn: DBConn) -> None:
    """Add any company_stores columns missing from an older database."""
    for column, col_type in _COMPANY_STORE_ADDED_COLUMNS.items():
        # DDL with hardcoded column/type from a module constant — not a LiteralString
        # to the stub, but no user input ever reaches it.
        conn.execute(  # ty: ignore[no-matching-overload]
            f"ALTER TABLE company_stores ADD COLUMN IF NOT EXISTS {column} {col_type}"
        )


def _migrate_state_programs(conn: DBConn) -> None:
    """Add any state_programs columns missing from an older database."""
    for column, col_type in _STATE_PROGRAM_ADDED_COLUMNS.items():
        # DDL with hardcoded column/type from a module constant (see above).
        conn.execute(  # ty: ignore[no-matching-overload]
            f"ALTER TABLE state_programs ADD COLUMN IF NOT EXISTS {column} {col_type}"
        )


def insert_dispensary(conn: DBConn, record: DispensaryRecord) -> None:
    """Insert one DispensaryRecord. Caller must commit."""
    now = datetime.datetime.now(datetime.UTC).isoformat()
    conn.execute(
        _INSERT_DISPENSARY,
        (
            record.source,
            record.name,
            record.address,
            record.city,
            record.state,
            record.zip_code,
            record.phone,
            record.website,
            record.latitude,
            record.longitude,
            now,
        ),
    )


def upsert_recon(conn: DBConn, record: CompanyReconRecord) -> None:
    """Upsert one CompanyReconRecord. Caller must commit."""
    now = datetime.datetime.now(datetime.UTC).isoformat()
    conn.execute(
        _UPSERT_RECON,
        (
            record.company_id,
            record.canonical_name,
            record.homepage_url,
            record.platform,
            record.confidence,
            record.http_status,
            record.error,
            now,
        ),
    )


def insert_company_store(conn: DBConn, record: CompanyStoreRecord) -> None:
    """Insert one CompanyStoreRecord. Caller must commit."""
    now = datetime.datetime.now(datetime.UTC).isoformat()
    conn.execute(
        _INSERT_COMPANY_STORE,
        (
            record.company_id,
            record.canonical_name,
            record.state,
            record.source,
            record.name,
            record.address,
            record.city,
            record.zip_code,
            record.phone,
            record.website,
            record.latitude,
            record.longitude,
            record.platform,
            record.external_id,
            record.store_url,
            now,
        ),
    )


def delete_company_stores_for_company(conn: DBConn, company_id: int, abbr: str) -> int:
    """Delete one company's store rows in a state so its re-scrape replaces them.

    Per-company (not whole-state) so a transient zero-yield for one company never
    wipes another company's good rows. Returns rows deleted; caller must commit.
    """
    cur = conn.execute(
        "DELETE FROM company_stores WHERE company_id = %s AND state = %s",
        (company_id, abbr),
    )
    return cur.rowcount


def count_company_stores(conn: DBConn, company_id: int, abbr: str) -> int:
    """How many stores are currently stored for one company in a state."""
    row = conn.execute(
        "SELECT COUNT(*) FROM company_stores WHERE company_id = %s AND state = %s",
        (company_id, abbr),
    ).fetchone()
    return row[0] if row else 0


def _distinct_stored_stores(conn: DBConn, company_id: int, abbr: str) -> int:
    """Stored DISTINCT physical stores (by address, name as fallback) for a company."""
    row = conn.execute(
        "SELECT COUNT(DISTINCT lower(coalesce(nullif(trim(address), ''), name, ''))) "
        "FROM company_stores WHERE company_id = %s AND state = %s",
        (company_id, abbr),
    ).fetchone()
    return row[0] if row else 0


def _distinct_new_stores(records: list[CompanyStoreRecord]) -> int:
    """Distinct physical stores in a scrape result (mirrors _distinct_stored_stores)."""
    return len({
        ((record.address or "").strip() or record.name or "").lower()
        for record in records
    })


# Weedmaps/Leafly are last-resort DIRECTORY listings: a handle exists, but the operator's
# real menu usually isn't there (their Stage-3 rungs frequently return empty). A store
# discovered via a real platform rung (Jane/Dutchie/Sweed/Cresco/Hytiva/Trulieve/Curaleaf —
# whose `platform` may even read "custom") is "menu-bearing" and worth more than an
# aggregator row. So keep-the-best prefers the result with MORE menu-bearing stores even at
# a total-count loss, and never downgrades menu-bearing stores to aggregator-only ones.
_AGGREGATOR_SOURCES = frozenset({"weedmaps_directory", "leafly_directory"})
_AGGREGATOR_PLATFORMS = frozenset({"weedmaps", "leafly"})


def _distinct_stored_menu_stores(conn: DBConn, company_id: int, abbr: str) -> int:
    """Stored DISTINCT physical stores carrying a NON-aggregator (real-menu-rung) handle."""
    row = conn.execute(
        "SELECT COUNT(DISTINCT lower(coalesce(nullif(trim(address), ''), name, ''))) "
        "FROM company_stores WHERE company_id = %s AND state = %s "
        "AND external_id IS NOT NULL AND external_id != '' "
        "AND coalesce(source, '') NOT IN ('weedmaps_directory', 'leafly_directory') "
        "AND coalesce(platform, '') NOT IN ('weedmaps', 'leafly')",
        (company_id, abbr),
    ).fetchone()
    return row[0] if row else 0


def _distinct_new_menu_stores(records: list[CompanyStoreRecord]) -> int:
    """Distinct physical stores in a scrape result carrying a non-aggregator handle."""
    return len({
        ((record.address or "").strip() or record.name or "").lower()
        for record in records
        if record.external_id
        and (record.source or "") not in _AGGREGATOR_SOURCES
        and (record.platform or "") not in _AGGREGATOR_PLATFORMS
    })


# A handle-upgrade may overwrite slightly fewer stores only if it retains at least this
# fraction of them — the Stage-3 `external_id` is worth a small count loss, a big one isn't.
_HANDLE_UPGRADE_RETENTION = 0.8

# A real-menu-handle upgrade (aggregator/plain → Jane/Dutchie/…) may lose more stores than a
# bare handle-upgrade — empty aggregator rows are low-value — but must still retain at least
# this fraction (so a real 15→1 collapse is rejected while a 4→3 menu upgrade is accepted).
_MENU_UPGRADE_RETENTION = 0.5


def replace_company_stores(
    conn: DBConn,
    company_id: int,
    abbr: str,
    records: list[CompanyStoreRecord],
) -> tuple[int, bool]:
    """Guarded, quality-aware keep-the-best replace of one company's stores. Caller commits.

    Overwrites the company's rows when the new scrape yields **at least as many** stores as
    are stored (so a transient zero/low-yield re-run can't clobber good data) — and, on a
    tie, the fresher result wins. Both sides are counted as DISTINCT physical stores
    (address, name as fallback), not raw rows, so a noisy extractor that emitted two rows
    per store can't entrench itself against a clean result. As a quality refinement, a new
    result that adds Stage-3 ``external_id`` handles where the stored rows have none also
    wins even if it has slightly fewer stores (it must retain ≥
    ``_HANDLE_UPGRADE_RETENTION`` of them), since a store row with a menu handle is worth
    more than a bare address.

    Quality dominates count among menu-platform handles (Jane/Dutchie/Sweed/… — NOT the
    Weedmaps/Leafly directory listings, whose menus are usually empty): a result with **more**
    of them wins as long as it retains ≥ ``_MENU_UPGRADE_RETENTION`` of the stores (so 4 empty
    Leafly listings yield to 3 Jane handles, but a 15→1 collapse is still rejected), and a
    result with **fewer** never clobbers (no downgrading real menus to a bigger empty-aggregator
    sweep). Only when both sides have the same menu-platform count does the distinct-count /
    freshness / handle-upgrade logic below decide. Returns ``(resulting_count, kept_prior)`` —
    ``kept_prior`` is True when better prior data was retained.
    """
    existing = count_company_stores(conn, company_id, abbr)
    if not records:
        return existing, False

    existing_distinct = _distinct_stored_stores(conn, company_id, abbr)
    new_distinct = _distinct_new_stores(records)
    existing_menu = _distinct_stored_menu_stores(conn, company_id, abbr)
    new_menu = _distinct_new_menu_stores(records)
    if new_menu < existing_menu:
        # Never downgrade real-menu handles to fewer of them (or to aggregator-only rows),
        # even if the new set has more total stores — protects a Jane/Dutchie set from a
        # transient low-yield re-scrape or a larger empty-aggregator sweep.
        overwrite = False
    elif new_menu > existing_menu:
        # Gained real-menu handles (e.g. 4 empty Leafly listings → 3 Jane handles): accept
        # unless it would lose more than half the stores (a 15→1 collapse is still rejected).
        overwrite = new_distinct >= existing_distinct * _MENU_UPGRADE_RETENTION
    else:
        overwrite = new_distinct >= existing_distinct
        if not overwrite:
            handle_row = conn.execute(
                "SELECT COUNT(*) FROM company_stores WHERE company_id = %s AND state = %s "
                "AND external_id IS NOT NULL AND external_id != ''",
                (company_id, abbr),
            ).fetchone()
            existing_handles = handle_row[0] if handle_row else 0
            new_handles = sum(1 for record in records if record.external_id)
            overwrite = (
                existing_handles == 0
                and new_handles > 0
                and new_distinct >= existing_distinct * _HANDLE_UPGRADE_RETENTION
            )
    if not overwrite:
        return existing, True

    delete_company_stores_for_company(conn, company_id, abbr)
    for record in records:
        insert_company_store(conn, record)
    return len(records), False


def insert_store_product(conn: DBConn, record: StoreProductRecord) -> None:
    """Insert one StoreProductRecord. Caller must commit."""
    now = datetime.datetime.now(datetime.UTC).isoformat()
    conn.execute(
        _INSERT_STORE_PRODUCT,
        (
            record.company_id,
            record.state,
            record.store_key,
            record.platform,
            record.external_id,
            record.source,
            record.external_product_id,
            record.name,
            record.brand,
            record.category,
            record.category_std,
            record.category_overridden,
            record.product_type_std,
            record.product_type_defaulted,
            record.obtention_std,
            record.strain_type,
            record.strain_type_std,
            record.price,
            record.size_g,
            record.thc,
            record.cbd,
            record.thc_mg,
            record.cbd_mg,
            Jsonb(record.terpenes) if record.terpenes is not None else None,
            Jsonb(record.terpenes_std) if record.terpenes_std is not None else None,
            record.terp_total,
            record.terpenes_repaired,
            Jsonb(record.cannabinoids_std) if record.cannabinoids_std is not None else None,
            Jsonb(record.variants) if record.variants is not None else None,
            now,
        ),
    )


def count_store_products(conn: DBConn, store_key: str) -> int:
    """How many product rows are currently stored for one store."""
    row = conn.execute(
        "SELECT COUNT(*) FROM store_products WHERE store_key = %s", (store_key,)
    ).fetchone()
    return row[0] if row else 0


# A re-scrape that collapses to a small fraction of the stored snapshot is almost always a
# throttled PARTIAL fetch — the aggregator 406 soft-block truncates a menu mid-pagination and
# tends to drive a store to near-zero
# — not a genuine menu shrink. Keep the larger prior rather than overwrite it with a fragment,
# the way Stage-2 stores have keep-the-best. The guard only holds while the prior is still FRESH:
# a real shrink (or a store that truly lost most of its menu) still lands once the old snapshot
# ages past the window, so a store can never be wedged on stale data forever.
_MENU_RETAIN_FRACTION = 0.5
_MENU_RETAIN_MAX_AGE_HOURS = 48.0


def _snapshot_age_hours(conn: DBConn, store_key: str) -> float | None:
    """Hours since this store's current snapshot was taken, or None if it has none."""
    # Cast to timestamptz so the max is chronological, not a lexical string max — and so psycopg
    # returns a tz-aware datetime, removing the naive-timestamp parse this used to guard against.
    row = conn.execute(
        "SELECT max(scraped_at::timestamptz) FROM store_products WHERE store_key = %s",
        (store_key,),
    ).fetchone()
    if row is None or row[0] is None:
        return None
    return (datetime.datetime.now(datetime.UTC) - row[0]).total_seconds() / 3600.0


def replace_store_products(
    conn: DBConn, store_key: str, records: list[StoreProductRecord]
) -> int:
    """Replace one store's menu snapshot wholesale. Caller commits.

    Menus churn daily, so a complete re-scrape is the new truth — but two cases are
    guarded so a bad scrape can't destroy a good snapshot:

    - an EMPTY result keeps the prior snapshot (a transient fetch failure must not
      wipe a good menu);
    - a result that collapses to under ``_MENU_RETAIN_FRACTION`` of a still-fresh
      prior (younger than ``_MENU_RETAIN_MAX_AGE_HOURS``) is treated as a throttled
      PARTIAL fetch and rejected — a 406-truncated fragment must not overwrite a full
      snapshot. Once the prior ages out of the window a genuine shrink still lands.

    Returns the resulting product count (the kept prior count when a guard fires).
    """
    if not records:
        return count_store_products(conn, store_key)
    prior = count_store_products(conn, store_key)
    if prior and len(records) < prior * _MENU_RETAIN_FRACTION:
        age_hours = _snapshot_age_hours(conn, store_key)
        if age_hours is not None and age_hours < _MENU_RETAIN_MAX_AGE_HOURS:
            print(
                f"  store_menu: {store_key} kept prior {prior} products "
                f"(re-scrape yielded {len(records)} < {_MENU_RETAIN_FRACTION:.0%} of "
                f"a {age_hours:.0f}h-old snapshot — likely a throttled partial)"
            )
            return prior
    conn.execute("DELETE FROM store_products WHERE store_key = %s", (store_key,))
    for record in records:
        insert_store_product(conn, record)
    return len(records)


# Categories whose products feed the master-DB observation history. Widened from flower-only to every
# CONSUMABLE category (those carrying price/potency/terpene/cannabinoid signal worth a time series);
# Accessory / Other / uncategorized are excluded (gear + grab-bag, no chemistry). For mg-dosed
# categories (edibles/tinctures/beverages/capsules) the dose is folded into product_fingerprint
# (thc_mg/cbd_mg), so a 10mg vs 100mg gummy of the same name are distinct identities.
_OBSERVED_CATEGORIES = (
    "Flower", "Pre-Roll", "Vape", "Concentrate", "Edible",
    "Beverage", "Tincture", "Topical", "Capsule",
)


def _observation_changed(prev: tuple, record: StoreProductRecord) -> bool:
    """Whether a record's price/potency/terpenes/cannabinoids differ from the last observation ``prev``
    = (product_id, price, thc, cbd, thc_mg, cbd_mg, terp_total, terpenes_std, cannabinoids_std, date)."""
    return (
        prev[1] != record.price or prev[2] != record.thc or prev[3] != record.cbd
        or prev[4] != record.thc_mg or prev[5] != record.cbd_mg or prev[6] != record.terp_total
        or (prev[7] or None) != (record.terpenes_std or None)
        or (prev[8] or None) != (record.cannabinoids_std or None)
    )


def record_observations(
    conn: DBConn, store_key: str, records: list[StoreProductRecord],
    *, now: datetime.datetime | None = None,
) -> int:
    """Append price/potency/terpene history for a store's observed-category products. Caller commits.

    The master-DB write path, run alongside the snapshot replace:
    upsert each product's identity into ``products``, then APPEND a ``product_observations`` row when
    its price/potency/terpenes changed since the last observation at this store, or once a day as a
    presence heartbeat. Append-only — rows are never updated or deleted. Scoped to consumable
    categories (``_OBSERVED_CATEGORIES``). ``now`` (the observation timestamp) defaults to the current UTC time;
    it is injectable for tests. Returns the number of observation rows appended.
    """
    observed_at = now or datetime.datetime.now(datetime.UTC)
    by_fp: dict[str, StoreProductRecord] = {}
    for record in records:
        if record.category_std not in _OBSERVED_CATEGORIES:
            continue
        fingerprint = text.product_fingerprint(
            record.brand, record.name, record.size_g, record.product_type_std,
            thc_mg=record.thc_mg, cbd_mg=record.cbd_mg,
        )
        if fingerprint:
            by_fp[fingerprint] = record  # a menu may list one product twice — keep the last
    if not by_fp:
        return 0

    # Upsert product identities → fingerprint:id (first_seen kept; last_seen bumped on re-sight).
    fp_to_id: dict[str, int] = {}
    for fingerprint, record in by_fp.items():
        row = conn.execute(
            "INSERT INTO products (fingerprint, brand, name, category_std, product_type_std, "
            "obtention_std, strain_type_std, size_g) VALUES (%s, %s, %s, %s, %s, %s, %s, %s) "
            "ON CONFLICT (fingerprint) DO UPDATE SET last_seen = now() RETURNING id",
            (fingerprint, text.normalize_brand(record.brand or ""), record.name,
             record.category_std, record.product_type_std, record.obtention_std,
             record.strain_type_std, record.size_g),
        ).fetchone()
        assert row is not None  # INSERT ... RETURNING always yields a row
        fp_to_id[fingerprint] = row[0]

    # The last observation per product at this store, for change detection.
    last: dict[int, tuple] = {}
    for row in conn.execute(
        "SELECT DISTINCT ON (product_id) product_id, price, thc, cbd, thc_mg, cbd_mg, terp_total, "
        "terpenes_std, cannabinoids_std, scraped_at::date FROM product_observations "
        "WHERE store_key = %s AND product_id = ANY(%s) ORDER BY product_id, scraped_at DESC",
        (store_key, list(fp_to_id.values())),
    ):
        last[row[0]] = row

    appended = 0
    for fingerprint, record in by_fp.items():
        product_id = fp_to_id[fingerprint]
        prev = last.get(product_id)
        same_day = prev is not None and prev[9] == observed_at.date()
        if prev is not None and same_day and not _observation_changed(prev, record):
            continue  # already have today's row and nothing changed — no duplicate heartbeat
        conn.execute(
            "INSERT INTO product_observations (product_id, store_key, state, price, thc, cbd, "
            "thc_mg, cbd_mg, terpenes_std, terp_total, cannabinoids_std, scraped_at) "
            "VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)",
            (product_id, store_key, record.state, record.price, record.thc, record.cbd,
             record.thc_mg, record.cbd_mg,
             Jsonb(record.terpenes_std) if record.terpenes_std is not None else None,
             record.terp_total,
             Jsonb(record.cannabinoids_std) if record.cannabinoids_std is not None else None,
             observed_at),
        )
        appended += 1
    return appended


# ── store-lifecycle history primitives (orchestrated in the overlay, which owns the location_key
#    computation since the key builders live in sources/dedupe.py — see docs/store_history_design.md) ──

def get_company_store_rows(
    conn: DBConn, company_id: int, state: str
) -> list[tuple]:
    """The company's current stored rows (canonical + alias), for a store-observation pass.

    Returns ``(canonical_name, storefront_name, address, city, zip_code, latitude, longitude,
    platform, external_id)`` per row — the fields a store observation records."""
    return conn.execute(
        "SELECT canonical_name, storefront_name, address, city, zip_code, latitude, longitude, "
        "platform, external_id FROM company_stores WHERE company_id = %s AND state = %s",
        (company_id, state),
    ).fetchall()


def upsert_store_location(
    conn: DBConn, *, location_key: str, state: str, latitude: float | None,
    longitude: float | None, address: str | None, city: str | None, zip_code: str | None,
) -> int:
    """Upsert a physical-location identity, returning its id. Keeps ``first_seen``, bumps
    ``last_seen`` and refreshes the representative attrs on re-sight. Caller commits."""
    row = conn.execute(
        "INSERT INTO store_locations (location_key, state, latitude, longitude, address, city, "
        "zip_code) VALUES (%s, %s, %s, %s, %s, %s, %s) "
        "ON CONFLICT (location_key) DO UPDATE SET last_seen = now(), state = EXCLUDED.state, "
        "latitude = EXCLUDED.latitude, longitude = EXCLUDED.longitude, address = EXCLUDED.address, "
        "city = EXCLUDED.city, zip_code = EXCLUDED.zip_code RETURNING id",
        (location_key, state, latitude, longitude, address, city, zip_code),
    ).fetchone()
    assert row is not None  # INSERT ... RETURNING always yields a row
    return row[0]


def latest_store_observations(
    conn: DBConn, location_ids: list[int], source: str
) -> dict[int, tuple]:
    """The most recent observation per location for a source, for change detection. Returns
    ``location_id -> (operator, storefront_name, platform, external_id, address, city,
    observed_at::date)``."""
    if not location_ids:
        return {}
    rows = conn.execute(
        "SELECT DISTINCT ON (location_id) location_id, operator, storefront_name, platform, "
        "external_id, address, city, observed_at::date FROM store_observations "
        "WHERE source = %s AND location_id = ANY(%s) ORDER BY location_id, observed_at DESC",
        (source, location_ids),
    ).fetchall()
    return {row[0]: row[1:] for row in rows}


def append_store_observation(
    conn: DBConn, *, location_id: int, source: str, operator: str | None,
    storefront_name: str | None, platform: str | None, external_id: str | None,
    address: str | None, city: str | None, observed_at: datetime.datetime,
) -> None:
    """Append one append-only store observation. Caller commits."""
    conn.execute(
        "INSERT INTO store_observations (location_id, source, operator, storefront_name, platform, "
        "external_id, address, city, observed_at) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)",
        (location_id, source, operator, storefront_name, platform, external_id, address, city,
         observed_at),
    )


def record_location_observations(
    conn: DBConn, source: str, observations: dict[str, LocationObservation],
    *, now: datetime.datetime | None = None,
) -> int:
    """The shared store-lifecycle write engine: upsert identities, append what changed. Caller commits.

    ``observations`` is one :class:`LocationObservation` per ``location_key`` — the caller computes
    the keys (``dedupe`` lives above ``db`` in the layering) and collapses same-rooftop duplicates
    with its own preference rule. For each: upsert the identity into ``store_locations``
    (keep ``first_seen``), then APPEND a ``store_observations`` row when the observed
    operator/storefront/handle/address changed since the last observation for this
    ``(location, source)``, or once a day as a presence heartbeat. Append-only; both the Stage-2
    ``company_site`` and Stage-1 ``state_roster`` captures drive this one engine
    (docs/store_history_design.md). Returns the number of observation rows appended.
    """
    if not observations:
        return 0
    observed_at = now or datetime.datetime.now(datetime.UTC)
    by_location: dict[int, LocationObservation] = {}
    for location_key, obs in observations.items():
        location_id = upsert_store_location(
            conn, location_key=location_key, state=obs.state, latitude=obs.latitude,
            longitude=obs.longitude, address=obs.address, city=obs.city, zip_code=obs.zip_code,
        )
        by_location[location_id] = obs

    last = latest_store_observations(conn, list(by_location), source)
    appended = 0
    for location_id, obs in by_location.items():
        observed = (obs.operator, obs.storefront_name, obs.platform, obs.external_id,
                    obs.address, obs.city)
        prev = last.get(location_id)  # (operator, storefront, platform, external_id, address, city, date)
        same_day = prev is not None and prev[6] == observed_at.date()
        if prev is not None and same_day and prev[:6] == observed:
            continue  # already have today's row and nothing changed — no duplicate heartbeat
        append_store_observation(
            conn, location_id=location_id, source=source, operator=obs.operator,
            storefront_name=obs.storefront_name, platform=obs.platform,
            external_id=obs.external_id, address=obs.address, city=obs.city,
            observed_at=observed_at,
        )
        appended += 1
    return appended


def replace_lifecycle_events(
    conn: DBConn, state: str, events: list[LifecycleEventRecord],
) -> int:
    """Replace one state's derived ``store_lifecycle_events`` with ``events``. Caller commits.

    A wholesale replace, NOT the keep-the-best guard ``replace_company_stores`` uses. That guard
    protects a *scrape* — a live snapshot a transient failure could clobber. These rows are a
    *derivation* over the append-only log, so recomputing them is free, deterministic, and the only
    way to let later evidence revise an earlier verdict: a store called "closed" that reappears next
    cycle must lose that event. Fewer events than last time is therefore a legitimate outcome, and
    the log — not this table — is the thing that must never be lost.

    Returns the number of event rows written.
    """
    conn.execute("DELETE FROM store_lifecycle_events WHERE state = %s", (state,))
    for event in events:
        conn.execute(
            "INSERT INTO store_lifecycle_events (location_id, state, source, kind, occurred_on, "
            "operator, previous_operator, confidence, related_location_id) "
            "VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)",
            (event.location_id, event.state, event.source, event.kind, event.occurred_on,
             event.operator, event.previous_operator, event.confidence, event.related_location_id),
        )
    return len(events)


# The "kept menu-bearing store per handle" selector — only canonical rows
# (``canonical_company_id IS NULL``) that carry a Stage-3 scrape handle (``platform`` + a non-empty
# ``external_id``). Shared by :func:`get_menu_stores_for_state` (the row Stage 3 scrapes under) and
# :func:`realign_store_products_company` (the row a snapshot is re-filed under) so both resolve the
# SAME row per ``(platform, external_id)`` — a filter/tiebreak edit here can't drift them apart.
# Callers supply their own SELECT-list, the ``state = %s`` filter, and ``DISTINCT ON (platform,
# external_id)``.
_KEPT_HANDLE_WHERE = (
    "canonical_company_id IS NULL "
    "AND platform IS NOT NULL AND external_id IS NOT NULL AND external_id != ''"
)
_KEPT_HANDLE_ORDER = "ORDER BY platform, external_id, company_id"


# The "natural flower" filter for product analyses (potency forensics, chemovar clustering): the
# Flower category MINUS anything whose potency/terpenes are not the PLANT'S OWN fingerprint.
#
# Two exclusions, and they are different in kind:
#
# (a) ADULTERATED bud — sprayed/coated with added cannabinoids. The `Infused` product type plus the
#     name-tells the taxonomy misses (moonrock, kief-/dusted-/coated-/covered-), and the adulterant
#     substances that appear in the name of a coated bud (distillate, rosin, shatter, badder, wax,
#     dab, powder). "diamond" and "caviar" stay ALLOWED — they are mostly legitimate strain names
#     with normal THC ("Black Diamond"), so excluding them would drop real flower.
#
# (b) NOT BUD AT ALL — 168 rows whose name says cartridge/cart/pod/syringe. These are a STORE's
#     mislabel on the platform: the raw category really is "Flower" and we record it faithfully.
#
# A note on (b), because it corrects an earlier misdiagnosis in this file's history: there is NO
# category-misclassification bug in `normalize_category`. It was suspected 2026-07-13 when 11,117
# "natural flower" rows turned out to carry a physically impossible >45% THC — but recomputing the
# category for every one of them reproduces the stored value exactly, and 20k+ of them arrive with
# raw category "Flower" straight from Dutchie/Leafly/Weedmaps/Jane. The impossible numbers are the
# SOURCE's, not a bucketing error of ours; they are the infused-flower label problem (finding #108),
# whose name-based filter is explicitly a LOWER bound. This predicate contains what a name can catch;
# it cannot catch a mislabeled potency on a product that says nothing but "flower".
#
# A WHERE fragment over `store_products`; callers add their own SELECT-list/filters.
# Lineage (indica/sativa/hybrid) you may actually ANALYZE. Weedmaps' consumer payload carried a
# DEFAULTED lineage field, so every product it served came back "Indica" whether or not anyone had
# said so. The mapper was fixed on 2026-07-10 (#181: read `genetics_tag`, never `category.name`), but
# the fix only reaches rows scraped AFTER it — and Weedmaps is ~35% of all lineage rows, so the stale
# ones swamp any pooled analysis.
#
# The signature is unmistakable, and it is why this guard is a date and not a judgment call:
#
#   weedmaps scrapes 2026-06-18 .. 07-05 (pre-fix):  44.7% - 64.6% "Indica"   <- defaulted
#   weedmaps scrape  2026-07-10        (post-fix):   28.0% "Indica"           <- matches Dutchie's 28.0%
#   flower only, pre-fix:                            97.2% "Indica"           <- against a Hybrid-majority market
#
# Two shipped analyses were computed over the contaminated pool and had to be RETRACTED (see
# docs/analysis/indica_sativa_form.md). Gate every lineage analysis on this, not on `strain_type_std
# IS NOT NULL`, which is exactly the check that let it through.
_WEEDMAPS_LINEAGE_FIX = "2026-07-10T19:15:00+00:00"   # commit c3c89d3, 2026-07-10 15:15 -0400
TRUSTED_LINEAGE_WHERE = (
    "strain_type_std IS NOT NULL "
    f"AND NOT (platform = 'weedmaps' AND scraped_at < '{_WEEDMAPS_LINEAGE_FIX}')"
)

NATURAL_FLOWER_WHERE = "category_std = 'Flower' AND obtention_std IS NULL"

# ── LEAFLY'S POTENCY IS NOT TRUSTWORTHY (verified 2026-07-14) ────────────────────────────────────────
#
# THE FOURTH INSTANCE OF THE SAME CLASS: a value manufactured UPSTREAM and read by us as an observation.
#   1. Weedmaps `strain_type` — a defaulted field, 98.2% "Indica". Finding E1 RETRACTED.
#   2. Our own `product_type_std` `_defaults` — 759,927 flower rows carry a "Bud" no name ever said.
#   3. (Jane's `lab_result_urls`: a field that exists and is empty on 100% of products.)
#   4. **Leafly `thc`.**
#
# On NATURAL FLOWER (this file's own guard applied), the share of rows claiming an IMPOSSIBLE >= 40% THC:
#
#       leafly    13.29%      <-- 21x Dutchie
#       jane       3.03%
#       sweedpos   1.62%
#       weedmaps   0.74%
#       dutchie    0.62%
#
# Leafly is **8.4% of natural-flower rows and supplies 60% of the ENTIRE impossible tail.** Excluding it,
# the corpus-wide impossible share falls **1.85% -> 0.81%**. Cured bud cannot exceed ~35% total THC, so
# these are not products; they are a number. It is NOT our parser — the extractor regex-matches a single
# percent and structurally cannot double anything; Leafly's own feed returns `thcContentLabel='THC 62.39%'`
# for flower. And it is DIFFERENTIAL BY STATE (MD 50.5%, MO 40.5% vs CO 3.9%, OR 3.7%), which is the
# dangerous kind: STATE IS THE UNIT OF ANALYSIS in the potency-ceiling and inflation-by-jurisdiction work.
#
# CONTAMINATED AND MUST BE RE-RUN: #44 `potency_ceiling` (its "1.6-1.9% impossible" headline is >half a
# Leafly artifact), #108 `infused_flower` (its "2,191 unexplained impossible natural rows" is very likely
# this), and D2, whose forensic spine IS the impossible tail.
#
# Use this guard for ANY analysis of the potency DISTRIBUTION, its tail, or a jurisdiction contrast.
TRUSTED_POTENCY_WHERE: LiteralString = "platform IS DISTINCT FROM 'leafly'"


def trusted_potency_where(alias: LiteralString = "") -> LiteralString:
    """`TRUSTED_POTENCY_WHERE`, qualified for a joined query. See the block comment above.

    **Why the list is Leafly and ONLY Leafly — the test to apply before adding a platform (2026-07-17).**

    The convicting evidence is the *impossible* tail, never a high headline. Dried flower cannot assay
    >= 40% THC, so that share is a manufactured-value detector; ">= 30% looks high" is a market signal and
    excluding on it DELETES FINDINGS. The decisive form is WITHIN-STATE, which holds market and regulation
    fixed so platform is the only variable. Missouri, natural flower:

        leafly   n=5,649   >=30%: 50.31%   >=40%: 40.01%
        dutchie  n=26,048  >=30%:  4.56%   >=40%:  0.11%     <- same state. 364x on the impossible tail.

    **hytiva was TESTED AND ACQUITTED — do not add it.** It shows the corpus's highest >=30% share
    (63.85%), which looks damning until you measure: **100% of its rows are PA** (3,815/3,815), and PA is
    the inflation frontier. Within PA every platform runs high (jane 49.41, dutchie 45.37, sweedpos 39.62)
    and hytiva's impossible >=40% tail is **0.87% — LOWER than jane's 3.03%**, with >=50% at exactly zero.
    It respects the physical ceiling; its headline was a state effect read as a platform effect. Guarding
    it would delete PA's frontier, which is the D1/D2 flagship contrast (PA ~42% vs WA ~5%).

    So: a high share earns a MEASUREMENT, not a guard. Convict on the impossible tail, within state.
    """
    return f"{alias}.platform IS DISTINCT FROM 'leafly'" if alias else TRUSTED_POTENCY_WHERE


def natural_flower_where(alias: LiteralString = "") -> LiteralString:
    """`NATURAL_FLOWER_WHERE`, qualified for a joined query (`natural_flower_where("sp")`).

    **THE UNALIASED CONSTANT IS WHY THE GUARD GOT COPIED, AND THE COPY WAS WRONG.**
    `scripts/indica_sativa_consumer.py` needed `sp.`-prefixed columns, could not reuse the bare constant,
    and hand-rolled its own — which kept the OLD, SHORT regex and therefore silently admitted
    `cartridge | pods | syringe | distillate | rosin | shatter | wax | dabs | powder` rows that the
    canonical guard excludes. Concentrate rows mislabeled as `Flower` passed a live terpene→lineage
    analysis feeding D11.

    A constant that cannot be used in the query you have is a constant that will be retyped. So this is a
    FUNCTION: there is now no reason to copy it, and `test_reference_db.py` fails any script that does.
    """
    if not alias:
        return NATURAL_FLOWER_WHERE
    q: LiteralString = alias + "."   # `alias` is a LiteralString, so the f-string below stays one (PEP 675)
    return f"{q}category_std = 'Flower' AND {q}obtention_std IS NULL"


def us_jurisdictions_where(col: LiteralString = "state") -> LiteralString:
    """`<col> IN (SELECT abbr FROM state_programs WHERE country='US')` — the US-only guard, aliasable.

    Same lesson as above: the bare subquery constant was hand-inlined in **11 scripts** because they needed
    `po.state` / `sc.state` / `p.state` rather than a bare `state`. Give them a function and the copies stop.
    """
    return f"{col} IN {US_JURISDICTIONS_SUBQUERY}"


# The same predicate against the `products_normalized` VIEW, which renames `category_std AS category`.
# `obtention_std` is deliberately NOT renamed by the view, so this differs from the store_products
# spelling by exactly one word — `test_db.py` asserts the two stay in sync.
NATURAL_FLOWER_WHERE_NORMALIZED = "category = 'Flower' AND obtention_std IS NULL"

# US territories we hold menu data for. Federal territories price in USD and license their own
# programs, so they belong in a US price analysis — but they are NOT states, and an analysis that
# reports a per-state or state-vs-territory contrast must be able to hold them out.
US_TERRITORIES = ("PR",)

# A US-only guard for price analyses. Canadian stores price in CAD, so pooling them into a $/g figure
# (or a cross-market $/g ranking) is a category error — CAD read as USD looks spuriously cheap. Restrict
# to jurisdictions whose program is US-based; Canada is analyzed on its own terms in the canada_* scripts.
#
# "JURISDICTIONS", not "STATES", and the distinction is load-bearing: this includes **DC and Puerto
# Rico**. It was called `US_JURISDICTIONS_SUBQUERY`, which read as though it were the 50 states and silently
# disagreed with `_terpene_source.JURISDICTIONS["USA"]` — the same word naming two different
# populations in two live scripts. Use `US_EXCL_TERRITORIES_SUBQUERY` when PR must be held out.
# Usage: `... WHERE <price predicate> AND state IN {reference_db.US_JURISDICTIONS_SUBQUERY}`.
US_JURISDICTIONS_SUBQUERY = "(SELECT abbr FROM state_programs WHERE country = 'US')"

# The same, minus the territories above — the population for a "US states + DC" claim, and the one a
# matrix must use when it reports Puerto Rico as its own column (otherwise PR is double-counted).
# `test_reference_db.py` asserts this is exactly `US_JURISDICTIONS_SUBQUERY` less `US_TERRITORIES`,
# so adding a territory to the tuple without updating the SQL fails the build rather than the analysis.
US_EXCL_TERRITORIES_SUBQUERY = (
    "(SELECT abbr FROM state_programs WHERE country = 'US' AND abbr <> 'PR')"
)

# The Canadian counterpart, for analyses that scope to Canada or contrast the two markets.
# The trap: `state = 'CA'` is CALIFORNIA. Canada is `country = 'CA'`, never a state literal.
CA_PROVINCES_SUBQUERY = "(SELECT abbr FROM state_programs WHERE country = 'CA')"



def get_menu_stores_for_state(conn: DBConn, abbr: str) -> list[tuple]:
    """Stores in a state that carry a Stage-3 menu handle, one row per store.

    Returns (company_id, canonical_name, source, platform, external_id, store_url,
    name, address, city) — ``source`` (the Stage-2 discovery rung) says which
    platform the external_id belongs to, which is what menu routing keys on;
    ``platform`` is the recon hint; address/city let a rung re-resolve a dubious
    captured id against a platform directory. Only canonical rows (shared-brand
    duplicates point at the same physical store) and only stores whose scrape
    stamped a platform + external_id; DISTINCT ON the handle so two operators
    sharing a storefront yield one menu job.
    """
    return conn.execute(
        "SELECT DISTINCT ON (platform, external_id) "
        "company_id, canonical_name, source, platform, external_id, store_url, name, "
        "address, city "
        "FROM company_stores "
        f"WHERE state = %s AND {_KEPT_HANDLE_WHERE} "
        f"{_KEPT_HANDLE_ORDER}",
        (abbr,),
    ).fetchall()


def latest_snapshot_times(conn: DBConn, abbr: str) -> dict[str, datetime.datetime]:
    """Most recent snapshot time per ``store_key`` for a state's menu snapshots.

    Drives Stage-3 freshness gating: a store whose latest snapshot is younger than
    the refresh window is skipped on the next run. ``scraped_at`` is cast to timestamptz so
    the max is chronological (not a lexical string max) and the values come back as tz-aware
    datetimes the caller compares directly — no string parsing.
    """
    rows = conn.execute(
        "SELECT store_key, max(scraped_at::timestamptz) FROM store_products "
        "WHERE state = %s GROUP BY store_key",
        (abbr,),
    ).fetchall()
    return dict(rows)


def get_recon_companies_for_state(
    conn: DBConn, abbr: str
) -> list[tuple[int, str, str, str | None]]:
    """Return (company_id, canonical_name, homepage_url, platform) for a state.

    Every recon'd company is returned, with ``homepage_url`` coalesced to ``''`` when the
    probe found no site. Companies with a homepage run the full own-site ladder; the
    homeless ones (``homepage == ''``) still get the homepage-INDEPENDENT Dutchie geo-sweep
    rung (it attributes by ``chain`` from the shared state pool), so a Dutchie operator is
    discoverable without seeding its homepage — see ``_company_catalog``.
    """
    return conn.execute(
        "SELECT cr.company_id, cr.canonical_name, COALESCE(cr.homepage_url, ''), cr.platform "
        "FROM company_recon cr JOIN companies c ON c.id = cr.company_id "
        "WHERE c.state = %s "
        "ORDER BY cr.canonical_name",
        (abbr,),
    ).fetchall()


def get_company_stores_for_dedupe(conn: DBConn, abbr: str) -> list[tuple]:
    """Return (id, company_id, canonical_name, name, address, city, zip_code,
    latitude, longitude, platform, external_id) rows — coordinates feed dedupe's
    geo-fallback key; platform + external_id let it keep the richest-menu handle per
    physical store (so a Dutchie/first-party store isn't demoted to its aggregator twin)."""
    return conn.execute(
        "SELECT id, company_id, canonical_name, name, address, city, zip_code, "
        "latitude, longitude, platform, external_id FROM company_stores "
        "WHERE state = %s ORDER BY id",
        (abbr,),
    ).fetchall()


def clear_store_canonical_for_state(conn: DBConn, abbr: str) -> None:
    """Reset all dedupe markers in a state so a fresh dedupe pass can re-decide."""
    conn.execute(
        "UPDATE company_stores SET canonical_company_id = NULL WHERE state = %s",
        (abbr,),
    )


def set_store_canonical(conn: DBConn, store_id: int, canonical_company_id: int) -> None:
    """Mark one company_store row as a duplicate of an operator's canonical company."""
    conn.execute(
        "UPDATE company_stores SET canonical_company_id = %s WHERE id = %s",
        (canonical_company_id, store_id),
    )


def realign_store_products_company(conn: DBConn, abbr: str) -> int:
    """Re-point a state's menu snapshots at the CURRENT kept company row for each handle.

    A snapshot is stamped with the company_id that owned its ``(platform, external_id)`` handle
    when it was scraped. A later dedupe can move the kept (canonical) row to a different company
    of the same operator cluster — Sunnyside's PA stores were scraped under the "Delta 9
    Pittsburgh" alias, then dedupe made "Sunnyside" canonical — but the snapshots keep the stale
    id, so per-operator menu reporting mis-attributes them. This re-stamps every snapshot to the
    company of the current kept row (``canonical_company_id IS NULL``, DISTINCT ON the handle),
    which is exactly the row :func:`get_menu_stores_for_state` scrapes under, so a snapshot is
    always filed under the same company a fresh scrape would use. Idempotent; returns rows moved.

    Handle-scoped: re-attribution keys on ``(platform, external_id)``, so a snapshot whose OWN
    handle was the folded (non-kept) side of a cross-handle merge maps to no kept row and keeps its
    prior company_id — a rare residual (one rooftop menu-scraped under two distinct handles, then
    folded; the folded row still exists, so the snapshot is not an orphan the menu-prune would catch).
    """
    cur = conn.execute(
        "UPDATE store_products sp SET company_id = k.company_id "
        "FROM (SELECT DISTINCT ON (platform, external_id) platform, external_id, company_id "
        "      FROM company_stores "
        f"      WHERE state = %s AND {_KEPT_HANDLE_WHERE} "
        f"      {_KEPT_HANDLE_ORDER}) k "
        "WHERE sp.state = %s AND sp.platform = k.platform AND sp.external_id = k.external_id "
        "  AND sp.company_id <> k.company_id",
        (abbr, abbr),
    )
    return cur.rowcount


def set_store_storefront(conn: DBConn, store_id: int, storefront_name: str) -> None:
    """Stamp the storefront (display) brand onto one store. Caller commits."""
    conn.execute(
        "UPDATE company_stores SET storefront_name = %s WHERE id = %s",
        (storefront_name, store_id),
    )


def set_store_location(
    conn: DBConn,
    store_id: int,
    latitude: float,
    longitude: float,
    address: str | None,
    zip_code: str | None,
) -> None:
    """Carry a geocoded sibling's coordinates (and a backfilled address/zip) onto a kept store.

    Used by dedupe when the row that won the kept slot is an address-less handle duplicate but a
    folded sibling has coordinates — so the surviving row still plots on the maps. Caller commits."""
    conn.execute(
        "UPDATE company_stores SET latitude = %s, longitude = %s, address = %s, zip_code = %s "
        "WHERE id = %s",
        (latitude, longitude, address, zip_code, store_id),
    )


_CREATE_STATE_PROGRAMS = """
CREATE TABLE IF NOT EXISTS state_programs (
    abbr         TEXT PRIMARY KEY,
    name         TEXT NOT NULL,
    programs     TEXT NOT NULL,
    program_term TEXT,
    agency       TEXT,
    best_url     TEXT,
    source_type  TEXT,
    all_gov_urls TEXT,
    last_checked TEXT,
    check_status TEXT NOT NULL DEFAULT 'never',
    searched_at  TEXT,
    error        TEXT,
    list_url      TEXT,
    list_type     TEXT,
    list_found_at TEXT,
    list_status   TEXT,
    country       TEXT NOT NULL DEFAULT 'US'
)
"""

# Columns added after the original state_programs schema shipped. create_tables()
# adds any that are missing so existing databases upgrade in place.
_STATE_PROGRAM_ADDED_COLUMNS = {
    "list_url": "TEXT",
    "list_type": "TEXT",
    "list_found_at": "TEXT",
    "list_status": "TEXT",
    "country": "TEXT NOT NULL DEFAULT 'US'",
}

_UPSERT_STATE_PROGRAM = """
INSERT INTO state_programs
  (abbr, name, programs, program_term, agency, best_url, source_type,
   all_gov_urls, last_checked, check_status, searched_at, error, country)
VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
ON CONFLICT (abbr) DO UPDATE SET
  best_url     = excluded.best_url,
  source_type  = excluded.source_type,
  all_gov_urls = excluded.all_gov_urls,
  last_checked = excluded.last_checked,
  check_status = excluded.check_status,
  searched_at  = excluded.searched_at,
  error        = excluded.error,
  country      = excluded.country
"""


def upsert_state_program(conn: DBConn, record: StateProgramRecord) -> None:
    """Upsert one StateProgramRecord. Caller must commit."""
    conn.execute(
        _UPSERT_STATE_PROGRAM,
        (
            record.abbr,
            record.name,
            record.programs,
            record.program_term,
            record.agency,
            record.best_url,
            record.source_type,
            json.dumps(record.all_gov_urls),
            record.last_checked,
            record.check_status,
            record.searched_at,
            record.error,
            record.country,
        ),
    )


def get_state_program(conn: DBConn, abbr: str) -> StateProgramRecord | None:
    """Return the stored StateProgramRecord for a state, or None."""
    row = conn.execute(
        "SELECT abbr, name, programs, program_term, agency, best_url, source_type, "
        "all_gov_urls, last_checked, check_status, searched_at, error, "
        "list_url, list_type, list_found_at, list_status, country "
        "FROM state_programs WHERE abbr = %s",
        (abbr,),
    ).fetchone()
    if row is None:
        return None
    return _row_to_state_program(row)


def get_all_state_programs(conn: DBConn) -> list[StateProgramRecord]:
    """Return all stored StateProgramRecords ordered by state name."""
    rows = conn.execute(
        "SELECT abbr, name, programs, program_term, agency, best_url, source_type, "
        "all_gov_urls, last_checked, check_status, searched_at, error, "
        "list_url, list_type, list_found_at, list_status, country "
        "FROM state_programs ORDER BY name"
    ).fetchall()
    return [_row_to_state_program(row) for row in rows]


def _row_to_state_program(row: tuple) -> StateProgramRecord:
    abbr, name, programs, program_term, agency, best_url, source_type, \
        all_gov_urls_json, last_checked, check_status, searched_at, error, \
        list_url, list_type, list_found_at, list_status, country = row
    all_gov_urls: list[str] = []
    if all_gov_urls_json:
        with contextlib.suppress(ValueError, TypeError):
            all_gov_urls = json.loads(all_gov_urls_json)
    return StateProgramRecord(
        abbr=abbr,
        name=name,
        programs=programs,
        program_term=program_term or "",
        agency=agency or "",
        best_url=best_url,
        source_type=source_type,
        all_gov_urls=all_gov_urls,
        last_checked=last_checked,
        check_status=check_status or "never",
        searched_at=searched_at,
        error=error,
        list_url=list_url,
        list_type=list_type,
        list_found_at=list_found_at,
        list_status=list_status,
        country=country or "US",
    )


def set_state_list(
    conn: DBConn,
    abbr: str,
    list_url: str | None,
    list_type: str | None,
    list_status: str,
) -> None:
    """Update only the dispensary-list columns for a state. Caller must commit.

    Kept separate from upsert_state_program so the search/verify flow (which builds
    records without list data) never clobbers a discovered list URL.
    """
    now = datetime.datetime.now(datetime.UTC).isoformat()
    conn.execute(
        "UPDATE state_programs "
        "SET list_url = %s, list_type = %s, list_found_at = %s, list_status = %s "
        "WHERE abbr = %s",
        (list_url, list_type, now, list_status, abbr),
    )


def delete_dispensaries_for_state(conn: DBConn, abbr: str) -> int:
    """Delete all dispensary rows for a state so a re-scrape replaces them.

    Returns the number of rows deleted; caller must commit.

    **This destroys derived location columns**, which the source will not republish. Every caller
    that re-inserts must follow the insert with :func:`apply_geocode_cache` — see the block comment
    above ``_CREATE_GEOCODE_CACHE``.
    """
    cur = conn.execute("DELETE FROM dispensaries WHERE state = %s", (abbr,))
    return cur.rowcount


# The tables carrying geocodable addresses: the ROSTER side (`dispensaries`) and the company's own
# store list (`company_stores`). Both feed `compare`, and both are replaced wholesale by a re-scrape.
GEOCODED_TABLES: tuple[LiteralString, ...] = ("dispensaries", "company_stores")


def put_geocode_cache(conn: DBConn, query: str, latitude: float | None, longitude: float | None,
                      zip_code: str | None, city: str | None) -> None:
    """Remember one geocoder result, keyed by its one-line query. Caller must commit.

    Overwrites on conflict: a later geocode of the same address is a better reading of it, not a
    second fact about it.
    """
    conn.execute(
        "INSERT INTO geocode_cache (query, latitude, longitude, zip_code, city) "
        "VALUES (%s, %s, %s, %s, %s) "
        "ON CONFLICT (query) DO UPDATE SET latitude = EXCLUDED.latitude, "
        "longitude = EXCLUDED.longitude, zip_code = EXCLUDED.zip_code, city = EXCLUDED.city, "
        "geocoded_at = now()",
        (query, latitude, longitude, zip_code, city),
    )


def get_geocode_cache(conn: DBConn, queries: list[str]) -> dict[str, tuple]:
    """Look up many cached geocodes at once -> ``{query: (lat, lon, zip_code, city)}``.

    Missing queries are simply absent from the mapping.
    """
    if not queries:
        return {}
    rows = conn.execute(
        "SELECT query, latitude, longitude, zip_code, city FROM geocode_cache "
        "WHERE query = ANY(%s)",
        (queries,),
    ).fetchall()
    return {row[0]: (row[1], row[2], row[3], row[4]) for row in rows}


def apply_geocode_cache(conn: DBConn, table: LiteralString, state: str | None = None) -> int:
    """Restore cached lat/lon/ZIP/city onto rows that are missing them. Caller must commit.

    Returns the number of rows that gained at least one value. Costs no geocoder calls, so it is
    cheap enough to run after every roster replace — which is the point: the command that destroys
    the enrichment is the command that puts it back.

    Each column is guarded by its own ``IS NULL``, so a value the SOURCE published is never
    overwritten by a cached geocoder guess. The source stays authoritative; the cache only fills
    what the source left empty.
    """
    if table not in GEOCODED_TABLES:
        raise ValueError(f"{table!r} is not a geocoded table; expected one of {GEOCODED_TABLES}")
    where = "(latitude IS NULL OR zip_code IS NULL OR city IS NULL) AND address IS NOT NULL"
    params: tuple = ()
    if state:
        where += " AND state = %s"
        params = (state,)
    rows = conn.execute(
        f"SELECT id, address, city, state, zip_code FROM {table} WHERE {where} ORDER BY id",
        params,
    ).fetchall()
    keyed = {
        row[0]: query
        for row in rows
        if (query := text.geocode_query(row[1], row[2], row[3], row[4])) is not None
    }
    cached = get_geocode_cache(conn, sorted(set(keyed.values())))

    restored = 0
    for row_id, query in keyed.items():
        hit = cached.get(query)
        if hit is None:
            continue
        latitude, longitude, zip_code, city = hit
        touched = 0
        if latitude is not None and longitude is not None:
            touched += conn.execute(
                f"UPDATE {table} SET latitude = %s, longitude = %s "
                "WHERE id = %s AND latitude IS NULL",
                (latitude, longitude, row_id),
            ).rowcount
        if zip_code:
            touched += conn.execute(
                f"UPDATE {table} SET zip_code = %s WHERE id = %s AND zip_code IS NULL",
                (zip_code, row_id),
            ).rowcount
        if city:
            touched += conn.execute(
                f"UPDATE {table} SET city = %s WHERE id = %s AND city IS NULL",
                (city, row_id),
            ).rowcount
        restored += bool(touched)
    return restored
