import datetime
from collections import Counter, defaultdict
from pathlib import Path

from rung import db
from rung.text import (
    extract_brand,
    is_placeholder_name,
    load_company_aliases,
    normalize_brand,
    readability_key,
)

_YAML_PATH = Path(__file__).parent / "data" / "companies.yml"


def canonicalize(raw_brand: str, alias_map: dict[str, str]) -> str:
    return alias_map.get(raw_brand, raw_brand)


def dominant_spelling(spellings: Counter[str]) -> str:
    """The display name for a folded brand group: the most frequent spelling in the roster,
    tie-broken toward the most readable (more spaces, then longer, then alphabetical) so the
    choice is deterministic — e.g. "Zen Leaf" wins over "ZenLeaf" when they tie."""
    return max(spellings, key=lambda s: (spellings[s], *readability_key(s)))


def _collect_brand_state_pairs(
    conn: db.DBConn, alias_map: dict[str, str]
) -> list[tuple[str, str]]:
    # Fold spelling/spacing/case variants of one brand (that companies.yml doesn't alias) into
    # a single company per (normalized-brand, state), seeded under the dominant spelling — so a
    # chain like Zen Leaf / ZenLeaf or NuEra / nuEra collapses to one operator instead of N.
    groups: dict[tuple[str, str], Counter[str]] = defaultdict(Counter)
    for name, city, state in conn.execute("SELECT name, city, state FROM dispensaries"):
        if is_placeholder_name(name):
            continue  # never seed a junk roster row (license-number/header/test stub) as a company
        # Pass the row's own city so a storefront suffix folds ("Zen Leaf Dayton" -> "Zen Leaf").
        canonical = canonicalize(extract_brand(name, city), alias_map)
        state_val = state if state else "Unknown"
        groups[(normalize_brand(canonical), state_val)][canonical] += 1
    pairs = {
        (dominant_spelling(spellings), state_val)
        for (_, state_val), spellings in groups.items()
    }
    return sorted(pairs)


def create_companies_table(conn: db.DBConn) -> None:
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS companies (
            id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            canonical_name TEXT NOT NULL,
            state          TEXT NOT NULL,
            created_at     TEXT NOT NULL,
            UNIQUE (canonical_name, state)
        )
        """
    )
    conn.commit()


def ensure_company(conn: db.DBConn, canonical_name: str, state: str) -> int:
    """Get-or-create the operator's companies row for (canonical_name, state); return its id.

    The get-or-create shared by the direct seeders (government monopolies, Shopify storefronts)
    that bypass the roster-derived `seed-companies` flow. Caller commits.
    """
    row = conn.execute(
        "SELECT id FROM companies WHERE canonical_name = %s AND state = %s",
        (canonical_name, state),
    ).fetchone()
    if row is not None:
        return int(row[0])
    now = datetime.datetime.now(datetime.UTC).isoformat()
    inserted = conn.execute(
        "INSERT INTO companies (canonical_name, state, created_at) VALUES (%s,%s,%s) RETURNING id",
        (canonical_name, state, now),
    ).fetchone()
    assert inserted is not None                  # INSERT ... RETURNING always yields the new row
    return int(inserted[0])


def _seed(
    conn: db.DBConn, pairs: list[tuple[str, str]]
) -> tuple[list[tuple[str, str]], int]:
    inserted: list[tuple[str, str]] = []
    skipped = 0
    for canonical_name, state in pairs:
        row = conn.execute(
            "SELECT COUNT(*) FROM companies WHERE canonical_name = %s AND state = %s",
            (canonical_name, state),
        ).fetchone()
        if row is not None and row[0] == 0:
            now = datetime.datetime.now(datetime.UTC).isoformat()
            conn.execute(
                "INSERT INTO companies (canonical_name, state, created_at) VALUES (%s,%s,%s)",
                (canonical_name, state, now),
            )
            inserted.append((canonical_name, state))
        else:
            skipped += 1
    conn.commit()
    return inserted, skipped


def main() -> None:
    alias_map = load_company_aliases(_YAML_PATH, strict=True)
    conn = db.get_connection()
    create_companies_table(conn)
    pairs = _collect_brand_state_pairs(conn, alias_map)
    inserted, skipped = _seed(conn, pairs)
    conn.close()

    print(f"Seeded companies table: {len(inserted)} inserted, {skipped} already present.")
    for canonical_name, state in inserted:
        print(f"  {canonical_name}  ({state})")


if __name__ == "__main__":
    main()
